@auther: Mitul Patel --> https://github.com/mitul19
Import libraries

In [1]:
import pandas as pd
import time
from datetime import datetime, date, timedelta
import yfinance as yf

from utils import *  #Our local functions.

In [2]:
# Reload utils module to get the updated functions
import importlib
import utils
importlib.reload(utils)
from utils import *

In [3]:
df = pd.read_csv('./indices/fo.csv')
df.tail(5)

         Symbol
201   DELHIVERY
202   PPLPHARMA
203   DALBHARAT
204      NUVAMA
205  OBEROIRLTY

Select Dates for analysis

In [4]:
# Dates 
dates = dict()
dates['startDate'] = str(date.today() - timedelta(days=365))
dates['date6M'] = str(date.today() - timedelta(days=180))
dates['endDate'] = str(date.today() - timedelta(days=1))

print('Start Date: ', dates['startDate'])
print('6M Date: ', dates['date6M'])
print('End Date: ', dates['endDate'])

Start Date:  2025-03-10
6M Date:  2025-09-11
End Date:  2026-03-09

In [5]:
# Create Yahoo symbol
df['Yahoo_Symbol'] = df.Symbol + '.NS'
df = df.set_index('Yahoo_Symbol')
symbol = list(df.index)
symbol[1]

'ICICIBANK.NS'

In [6]:
# yf data
# yf data dowload in chunkns
CHUNK = 50
close = []
for k in range(0, len(symbol), CHUNK):
    print(k, end = ',', flush = True)
    _symlist = symbol[k:k+CHUNK]
    _x = yf.download(_symlist, start = dates['startDate'], progress = False, auto_adjust=True)['Close']
    close = _x if len(close) == 0 else pd.concat([close, _x], axis = 1)
    time.sleep(.5)
close

0,50,100,150,200,

Ticker,AXISBANK.NS,BAJAJ-AUTO.NS,BAJFINANCE.NS,BEL.NS,BHARTIARTL.NS,BPCL.NS,BSE.NS,COALINDIA.NS,DIXON.NS,EICHERMOT.NS,...,TIINDIA.NS,TORNTPOWER.NS,VOLTAS.NS,ZYDUSLIFE.NS,DALBHARAT.NS,DELHIVERY.NS,EXIDEIND.NS,NUVAMA.NS,OBEROIRLTY.NS,PPLPHARMA.NS
Date,,,,,,,,,,,,,,,,,,,,,
2025-03-10,1034.965454,7200.900879,829.143799,269.057739,1617.428467,241.156464,1328.792358,350.507599,13125.309570,4926.667969,...,2710.916504,1331.270386,1389.990845,883.578308,1666.468384,250.820007,345.091095,1004.495789,1516.568604,200.420151
2025-03-11,1024.774170,7314.570312,828.930054,275.366150,1649.163086,248.336823,1265.923950,354.151398,13292.984375,4921.731934,...,2878.139160,1315.983643,1398.294434,889.658630,1679.163330,248.380005,342.803101,932.151123,1573.835938,201.279587
2025-03-12,1010.336548,7329.296387,843.241760,275.018463,1629.229736,249.970016,1333.926147,355.693024,13073.131836,4953.224121,...,2913.990479,1297.787720,1437.426025,878.190063,1634.009155,240.289993,338.873688,940.852417,1563.089111,201.689331
2025-03-13,1009.337402,7319.202637,836.880981,278.237274,1618.965576,248.177246,1304.635254,353.450653,13318.123047,4951.051758,...,2922.578857,1273.427612,1394.764282,873.098328,1600.156128,241.759995,331.263580,918.127319,1525.971924,201.709305
2025-03-17,1033.266968,7301.013184,852.772888,278.098175,1625.560547,245.370834,1316.630737,360.411316,13092.374023,4985.604004,...,2829.904785,1292.757935,1450.353882,882.589661,1656.162964,242.399994,332.407593,972.188171,1512.985962,205.796661
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-03-04,1351.300049,9652.500000,945.099976,444.955750,1905.900024,356.399994,2626.899902,435.149994,10136.000000,7626.500000,...,2771.100098,1475.900024,1438.900024,896.900024,1895.699951,416.700012,313.950012,1196.500000,1454.400024,152.309998
2026-03-05,1349.099976,9804.500000,962.400024,458.049988,1907.000000,360.350006,2761.399902,449.399994,10224.000000,7755.000000,...,2781.899902,1503.900024,1485.300049,914.650024,1928.699951,428.100006,319.649994,1238.099976,1482.099976,153.300003
2026-03-06,1315.800049,9816.000000,950.200012,468.450012,1870.800049,352.750000,2751.600098,440.450012,10029.000000,7620.500000,...,2722.899902,1481.300049,1478.400024,913.049988,1899.800049,422.600006,315.950012,1225.099976,1474.599976,151.869995
2026-03-09,1288.300049,9383.000000,938.049988,457.350006,1866.699951,331.149994,2768.899902,437.649994,9804.000000,7266.000000,...,2608.600098,1428.900024,1436.500000,908.849976,1840.199951,415.649994,308.899994,1208.400024,1469.500000,151.399994
2026-03-10,1311.000000,9539.000000,943.000000,NaN,1851.300049,325.149994,2869.000000,441.200012,10353.000000,NaN,...,2617.600098,1441.699951,1441.800049,920.299988,1844.400024,423.049988,313.000000,1230.599976,1477.800049,153.270004

In [7]:
# # Keep the data within the date range
# data12M = close[:endDate].copy()

# # At least 12 months of trading is required
# data12M.dropna(axis = 1, inplace = True)
# data12M

data12M = close[:dates['endDate']].copy()
data12M

Ticker,AXISBANK.NS,BAJAJ-AUTO.NS,BAJFINANCE.NS,BEL.NS,BHARTIARTL.NS,BPCL.NS,BSE.NS,COALINDIA.NS,DIXON.NS,EICHERMOT.NS,...,TIINDIA.NS,TORNTPOWER.NS,VOLTAS.NS,ZYDUSLIFE.NS,DALBHARAT.NS,DELHIVERY.NS,EXIDEIND.NS,NUVAMA.NS,OBEROIRLTY.NS,PPLPHARMA.NS
Date,,,,,,,,,,,,,,,,,,,,,
2025-03-10,1034.965454,7200.900879,829.143799,269.057739,1617.428467,241.156464,1328.792358,350.507599,13125.309570,4926.667969,...,2710.916504,1331.270386,1389.990845,883.578308,1666.468384,250.820007,345.091095,1004.495789,1516.568604,200.420151
2025-03-11,1024.774170,7314.570312,828.930054,275.366150,1649.163086,248.336823,1265.923950,354.151398,13292.984375,4921.731934,...,2878.139160,1315.983643,1398.294434,889.658630,1679.163330,248.380005,342.803101,932.151123,1573.835938,201.279587
2025-03-12,1010.336548,7329.296387,843.241760,275.018463,1629.229736,249.970016,1333.926147,355.693024,13073.131836,4953.224121,...,2913.990479,1297.787720,1437.426025,878.190063,1634.009155,240.289993,338.873688,940.852417,1563.089111,201.689331
2025-03-13,1009.337402,7319.202637,836.880981,278.237274,1618.965576,248.177246,1304.635254,353.450653,13318.123047,4951.051758,...,2922.578857,1273.427612,1394.764282,873.098328,1600.156128,241.759995,331.263580,918.127319,1525.971924,201.709305
2025-03-17,1033.266968,7301.013184,852.772888,278.098175,1625.560547,245.370834,1316.630737,360.411316,13092.374023,4985.604004,...,2829.904785,1292.757935,1450.353882,882.589661,1656.162964,242.399994,332.407593,972.188171,1512.985962,205.796661
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-03-02,1372.300049,9776.000000,978.250000,452.025665,1873.199951,374.799988,2643.600098,426.250000,10151.000000,7826.000000,...,2837.600098,1554.900024,1499.099976,906.900024,1959.500000,427.899994,322.799988,1206.500000,1490.699951,152.809998
2026-03-04,1351.300049,9652.500000,945.099976,444.955750,1905.900024,356.399994,2626.899902,435.149994,10136.000000,7626.500000,...,2771.100098,1475.900024,1438.900024,896.900024,1895.699951,416.700012,313.950012,1196.500000,1454.400024,152.309998
2026-03-05,1349.099976,9804.500000,962.400024,458.049988,1907.000000,360.350006,2761.399902,449.399994,10224.000000,7755.000000,...,2781.899902,1503.900024,1485.300049,914.650024,1928.699951,428.100006,319.649994,1238.099976,1482.099976,153.300003
2026-03-06,1315.800049,9816.000000,950.200012,468.450012,1870.800049,352.750000,2751.600098,440.450012,10029.000000,7620.500000,...,2722.899902,1481.300049,1478.400024,913.049988,1899.800049,422.600006,315.950012,1225.099976,1474.599976,151.869995
2026-03-09,1288.300049,9383.000000,938.049988,457.350006,1866.699951,331.149994,2768.899902,437.649994,9804.000000,7266.000000,...,2608.600098,1428.900024,1436.500000,908.849976,1840.199951,415.649994,308.899994,1208.400024,1469.500000,151.399994

In [8]:
# Get month end prices
dfMonthEnd = getMonthlyPrices(data12M)
dfMonthEnd

Ticker,AXISBANK.NS,BAJAJ-AUTO.NS,BAJFINANCE.NS,BEL.NS,BHARTIARTL.NS,BPCL.NS,BSE.NS,COALINDIA.NS,DIXON.NS,EICHERMOT.NS,...,TIINDIA.NS,TORNTPOWER.NS,VOLTAS.NS,ZYDUSLIFE.NS,DALBHARAT.NS,DELHIVERY.NS,EXIDEIND.NS,NUVAMA.NS,OBEROIRLTY.NS,PPLPHARMA.NS
Date,,,,,,,,,,,,,,,,,,,,,
2025-03-28,1101.058960,7684.104492,889.073914,299.348206,1719.029175,261.374084,1820.857056,372.043518,13173.637695,5279.246582,...,2765.592041,1466.384644,1450.602417,876.361023,1813.679565,255.100006,358.570465,1103.689087,1629.362061,224.604477
2025-04-30,1183.988159,7831.518555,858.154785,312.044586,1849.042236,291.015289,2113.002441,359.990875,16444.681641,5495.739258,...,2894.666992,1517.915527,1229.238159,878.190063,1934.306030,305.549988,349.915802,1107.104370,1633.541260,210.913345
2025-05-30,1191.181885,8394.256836,918.049988,382.083252,1840.810913,298.852692,2674.000000,371.202606,14685.464844,5265.228027,...,3057.944824,1355.088013,1255.790039,919.467224,2007.687622,358.000000,384.832794,1306.926270,1739.897339,206.166428
2025-06-30,1198.175903,8376.000000,936.500000,418.741760,1992.939209,311.570831,2770.100098,366.204071,14976.334961,5584.093750,...,3104.781250,1452.548706,1314.099976,978.738220,2203.461914,382.799988,385.728088,1569.053223,1898.613159,203.248322
2025-07-31,1068.400024,8008.000000,881.200012,380.593048,1914.300049,313.737671,2427.399902,351.628784,16833.507812,5398.500000,...,2838.295898,1296.565063,1327.699951,969.799988,2231.309326,425.250000,384.299988,1380.046387,1625.982788,197.029999
2025-08-29,1045.199951,8631.500000,877.849976,367.834045,1888.800049,293.634857,2096.199951,360.151672,16682.576172,6103.000000,...,2959.093750,1214.713257,1374.000000,981.049988,2396.998291,468.049988,396.250000,1216.964722,1606.731567,183.440002
2025-09-30,1131.599976,8678.500000,998.900024,402.237610,1878.400024,323.598541,2040.199951,374.709595,16322.000000,7005.500000,...,3094.079346,1206.399414,1353.500000,981.900024,2223.024902,450.049988,390.750000,1201.905151,1578.104126,191.160004
2025-10-31,1232.800049,8892.500000,1042.800049,424.293701,2054.500000,339.938049,2479.000000,373.460388,15494.000000,7007.000000,...,3020.441650,1302.998413,1383.599976,974.450012,2096.800049,465.950012,381.899994,1351.928833,1775.897217,199.630005
2025-11-28,1279.699951,9073.500000,1037.500000,410.004547,2101.600098,349.248169,2902.399902,371.242340,14601.000000,7053.500000,...,2782.043457,1301.018921,1376.300049,942.500000,2009.400024,426.200012,374.799988,1492.500000,1644.974243,187.210007
2025-12-31,1269.400024,9343.000000,986.799988,397.906036,2105.600098,373.465027,2632.199951,393.794220,12102.000000,7312.500000,...,2611.887939,1293.298828,1361.199951,914.349976,2130.899902,403.850006,362.200012,1480.500000,1668.342651,172.210007
2026-01-30,1370.400024,9597.500000,929.849976,447.096619,1968.699951,354.500000,2797.000000,434.999481,10446.000000,7122.500000,...,2333.124023,1373.369141,1327.900024,885.299988,2065.500000,422.950012,321.600006,1345.400024,1490.900024,154.679993
2026-02-27,1383.900024,9972.500000,995.900024,442.814880,1879.300049,385.399994,2707.100098,430.649994,10528.000000,8010.500000,...,2753.399902,1566.400024,1561.300049,921.700012,1993.000000,433.399994,334.299988,1244.900024,1522.800049,156.130005
2026-03-09,1288.300049,9383.000000,938.049988,457.350006,1866.699951,331.149994,2768.899902,437.649994,9804.000000,7266.000000,...,2608.600098,1428.900024,1436.500000,908.849976,1840.199951,415.649994,308.899994,1208.400024,1469.500000,151.399994

In [9]:
# Stats DataFrame
dfStats = pd.DataFrame()

# Rate of change
dfStats['roc1M'] = getNMonthRoC(dfMonthEnd, 1)
dfStats['roc3M'] = getNMonthRoC(dfMonthEnd, 3)
dfStats['roc6M'] = getNMonthRoC(dfMonthEnd, 6)
dfStats['roc12M'] = getNMonthRoC(dfMonthEnd, 11)
dfStats
# dfStats = dfStats.reset_index()
# print(dfStats)
# dfStats = dfStats.set_index("Ticker")
# print(dfStats)

               roc1M  roc3M  roc6M  roc12M
Ticker
AXISBANK.NS    -6.91   1.49  13.85    8.81
BAJAJ-AUTO.NS  -5.91   0.43   8.12   19.81
BAJFINANCE.NS  -5.81  -4.94  -6.09    9.31
BEL.NS          3.28  14.94  13.70   46.57
BHARTIARTL.NS  -0.67 -11.35  -0.62    0.95
...              ...    ...    ...     ...
DELHIVERY.NS   -4.10   2.92  -7.64   36.03
EXIDEIND.NS    -7.60 -14.72 -20.95  -11.72
NUVAMA.NS      -2.93 -18.38   0.54    9.15
OBEROIRLTY.NS  -3.50 -11.92  -6.88  -10.04
PPLPHARMA.NS   -3.03 -12.08 -20.80  -28.22

[206 rows x 4 columns]

In [10]:

# Data for the past 6 months
# midDate = str(date.today() - timedelta(days=180))

data6M = data12M[dates['date6M']:].copy()
data6M

Ticker,AXISBANK.NS,BAJAJ-AUTO.NS,BAJFINANCE.NS,BEL.NS,BHARTIARTL.NS,BPCL.NS,BSE.NS,COALINDIA.NS,DIXON.NS,EICHERMOT.NS,...,TIINDIA.NS,TORNTPOWER.NS,VOLTAS.NS,ZYDUSLIFE.NS,DALBHARAT.NS,DELHIVERY.NS,EXIDEIND.NS,NUVAMA.NS,OBEROIRLTY.NS,PPLPHARMA.NS
Date,,,,,,,,,,,,,,,,,,,,,
2025-09-11,1087.400024,9113.5,970.250000,383.517303,1913.000000,304.877197,2162.800049,377.976685,18032.974609,6758.0,...,3208.582520,1255.292725,1395.300049,1043.599976,2405.282715,470.299988,422.700012,1176.075195,1599.749390,200.160004
2025-09-12,1105.300049,8999.5,1003.250000,397.607300,1902.599976,302.971710,2201.199951,378.937622,18094.947266,6875.0,...,3228.465576,1254.797852,1403.599976,1044.750000,2406.879639,467.750000,418.549988,1228.307007,1597.854126,200.669998
2025-09-15,1104.400024,9025.0,1009.849976,396.760925,1904.500000,302.733521,2227.399902,379.321991,17977.000000,6801.0,...,3351.261719,1254.302979,1415.800049,1036.900024,2410.472900,470.950012,415.649994,1221.825684,1635.857788,203.690002
2025-09-16,1121.199951,9072.5,1003.250000,401.192047,1939.500000,303.209900,2199.300049,380.330933,18110.000000,6927.5,...,3401.518799,1248.958374,1414.599976,1034.500000,2423.348633,475.600006,418.200012,1215.916138,1638.850220,205.630005
2025-09-17,1126.000000,9084.0,1007.500000,410.452637,1941.300049,308.259399,2209.800049,384.126556,18110.000000,6890.5,...,3384.133789,1252.620361,1411.900024,1033.800049,2471.558105,482.600006,418.799988,1213.342773,1652.515625,203.130005
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-03-02,1372.300049,9776.0,978.250000,452.025665,1873.199951,374.799988,2643.600098,426.250000,10151.000000,7826.0,...,2837.600098,1554.900024,1499.099976,906.900024,1959.500000,427.899994,322.799988,1206.500000,1490.699951,152.809998
2026-03-04,1351.300049,9652.5,945.099976,444.955750,1905.900024,356.399994,2626.899902,435.149994,10136.000000,7626.5,...,2771.100098,1475.900024,1438.900024,896.900024,1895.699951,416.700012,313.950012,1196.500000,1454.400024,152.309998
2026-03-05,1349.099976,9804.5,962.400024,458.049988,1907.000000,360.350006,2761.399902,449.399994,10224.000000,7755.0,...,2781.899902,1503.900024,1485.300049,914.650024,1928.699951,428.100006,319.649994,1238.099976,1482.099976,153.300003
2026-03-06,1315.800049,9816.0,950.200012,468.450012,1870.800049,352.750000,2751.600098,440.450012,10029.000000,7620.5,...,2722.899902,1481.300049,1478.400024,913.049988,1899.800049,422.600006,315.950012,1225.099976,1474.599976,151.869995
2026-03-09,1288.300049,9383.0,938.049988,457.350006,1866.699951,331.149994,2768.899902,437.649994,9804.000000,7266.0,...,2608.600098,1428.900024,1436.500000,908.849976,1840.199951,415.649994,308.899994,1208.400024,1469.500000,151.399994

In [11]:
# Volatility
dfStats['volatility6M'] = getVolatility(getDailyReturns(data6M))
dfStats['volatility12M'] = getVolatility(getDailyReturns(data12M))

# Sharpe using RoC, annualised returns and Frog in the pan
dfStats['sharpe6MRoC'] = getSharpeRoC(dfStats['roc6M'], dfStats['volatility6M'])
dfStats['sharpe6M'] = getSharpe(getDailyReturns(data6M))
dfStats['FIP6M'] = getFIP(data6M) 

dfStats['sharpe12MRoC'] = getSharpeRoC(dfStats['roc12M'], dfStats['volatility12M'])
dfStats['sharpe12M'] = getSharpe(getDailyReturns(data12M))
dfStats['FIP12M'] = getFIP(data12M)

# dfStats = dfStats.set_index("Ticker")
dfStats

,roc1M,roc3M,roc6M,roc12M,volatility6M,volatility12M,sharpe6MRoC,sharpe6M,FIP6M,sharpe12MRoC,sharpe12M,FIP12M
Ticker,,,,,,,,,,,,
AXISBANK.NS,-6.91,1.49,13.85,8.81,21.76,22.18,0.64,1.73,12,0.40,1.12,-2
BAJAJ-AUTO.NS,-5.91,0.43,8.12,19.81,18.04,22.08,0.45,0.43,4,0.90,1.34,20
BAJFINANCE.NS,-5.81,-4.94,-6.09,9.31,25.94,26.08,-0.23,-0.14,-1,0.36,0.61,10
BEL.NS,3.28,14.94,13.70,46.57,26.62,26.53,0.51,1.50,6,1.76,2.18,4
BHARTIARTL.NS,-0.67,-11.35,-0.62,0.95,17.83,19.09,-0.03,-0.20,-2,0.05,0.86,0
...,...,...,...,...,...,...,...,...,...,...,...,...
DELHIVERY.NS,-4.10,2.92,-7.64,36.03,30.80,33.17,-0.25,-0.68,4,1.09,1.72,24
EXIDEIND.NS,-7.60,-14.72,-20.95,-11.72,20.32,23.56,-1.03,-3.10,-24,-0.50,-0.36,-14
NUVAMA.NS,-2.93,-18.38,0.54,9.15,32.45,38.56,0.02,0.16,-7,0.24,0.61,-8
OBEROIRLTY.NS,-3.50,-11.92,-6.88,-10.04,25.60,28.77,-0.27,-0.56,-4,-0.35,0.03,-8
PPLPHARMA.NS,-3.03,-12.08,-20.80,-28.22,25.80,28.84,-0.81,-2.11,-14,-0.98,-0.85,-14

In [12]:
# Get Nifty data
dfNifty = yf.download("^NSEI", start = dates['startDate'], progress = False, auto_adjust=True)['Close']
dfNifty = dfNifty.rename(columns = {'^NSEI':'Nifty'})
# dfNifty.reset_index()
dfNifty

Ticker             Nifty
Date
2025-03-10  22460.300781
2025-03-11  22497.900391
2025-03-12  22470.500000
2025-03-13  22397.199219
2025-03-17  22508.750000
...                  ...
2026-03-04  24480.500000
2026-03-05  24765.900391
2026-03-06  24450.449219
2026-03-09  24028.050781
2026-03-10  24202.900391

[247 rows x 1 columns]

In [13]:
# Get stock beta
dfStats['Beta'] = getBeta(dfNifty, data12M)

# close and ema
dfStats['Close'] = round(data12M.iloc[-1], 2)
dfStats['ema100d'] = round(data12M.ewm(span=100).mean().iloc[-1], 2)
dfStats

,roc1M,roc3M,roc6M,roc12M,volatility6M,volatility12M,sharpe6MRoC,sharpe6M,FIP6M,sharpe12MRoC,sharpe12M,FIP12M,Beta,Close,ema100d
Ticker,,,,,,,,,,,,,,,
AXISBANK.NS,-6.91,1.49,13.85,8.81,21.76,22.18,0.64,1.73,12,0.40,1.12,-2,1.17,1288.30,1285.76
BAJAJ-AUTO.NS,-5.91,0.43,8.12,19.81,18.04,22.08,0.45,0.43,4,0.90,1.34,20,1.08,9383.00,9364.41
BAJFINANCE.NS,-5.81,-4.94,-6.09,9.31,25.94,26.08,-0.23,-0.14,-1,0.36,0.61,10,1.14,938.05,983.48
BEL.NS,3.28,14.94,13.70,46.57,26.62,26.53,0.51,1.50,6,1.76,2.18,4,0.84,457.35,419.48
BHARTIARTL.NS,-0.67,-11.35,-0.62,0.95,17.83,19.09,-0.03,-0.20,-2,0.05,0.86,0,0.84,1866.70,2001.23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
DELHIVERY.NS,-4.10,2.92,-7.64,36.03,30.80,33.17,-0.25,-0.68,4,1.09,1.72,24,0.64,415.65,423.49
EXIDEIND.NS,-7.60,-14.72,-20.95,-11.72,20.32,23.56,-1.03,-3.10,-24,-0.50,-0.36,-14,1.16,308.90,353.03
NUVAMA.NS,-2.93,-18.38,0.54,9.15,32.45,38.56,0.02,0.16,-7,0.24,0.61,-8,1.28,1208.40,1351.06
OBEROIRLTY.NS,-3.50,-11.92,-6.88,-10.04,25.60,28.77,-0.27,-0.56,-4,-0.35,0.03,-8,1.44,1469.50,1597.27
PPLPHARMA.NS,-3.03,-12.08,-20.80,-28.22,25.80,28.84,-0.81,-2.11,-14,-0.98,-0.85,-14,1.04,151.40,172.03

In [14]:
# Apply filters: for buy and sell condition creation
cond1 = dfStats['Close'] > dfStats['ema100d']
cond2 = dfStats['sharpe6M'] > 0 
cond3 = dfStats['FIP12M'] > 0
cond4 = dfStats['sharpe12M'] > 0
cond5 = dfStats['FIP6M'] > 0
buyList = cond1 & cond2 & cond3 & cond4 & cond5
print([i for i in range(len(buyList)) if buyList.iloc[i] == True])
print([elem for i,elem in enumerate(buyList) if buyList.iloc[i] == True])
buyList

[1, 3, 7, 9, 11, 14, 30, 31, 32, 33, 37, 38, 39, 41, 42, 44, 49, 50, 51, 56, 58, 67, 70, 78, 81, 82, 85, 87, 92, 98, 107, 109, 114, 121, 123, 124, 128, 130, 133, 138, 143, 164, 197, 198]
[True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True]

Ticker
AXISBANK.NS      False
BAJAJ-AUTO.NS     True
BAJFINANCE.NS    False
BEL.NS            True
BHARTIARTL.NS    False
                 ...
DELHIVERY.NS     False
EXIDEIND.NS      False
NUVAMA.NS        False
OBEROIRLTY.NS    False
PPLPHARMA.NS     False
Length: 206, dtype: bool

In [15]:
sellcond1 = dfStats['Close'] < dfStats['ema100d']
sellcond2 = dfStats['sharpe6M'] < 0 
sellcond3 = dfStats['FIP12M'] < 0
sellcond4 = dfStats['sharpe12M'] < 0
sellcond5 = dfStats['FIP6M'] < 0
sellList = sellcond1 & sellcond2 & sellcond3 & sellcond4 & sellcond5
# sellList = sellcond1
print([i for i in range(len(sellList)) if sellList.iloc[i] == True])
print([elem for i,elem in enumerate(sellList) if sellList.iloc[i] == True])

sellList

[8, 21, 23, 36, 46, 47, 52, 68, 73, 80, 83, 88, 91, 93, 96, 99, 122, 125, 127, 136, 137, 140, 141, 147, 153, 158, 165, 166, 167, 169, 171, 173, 175, 179, 180, 184, 186, 192, 193, 195, 202, 205]
[True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True]

Ticker
AXISBANK.NS      False
BAJAJ-AUTO.NS    False
BAJFINANCE.NS    False
BEL.NS           False
BHARTIARTL.NS    False
                 ...
DELHIVERY.NS     False
EXIDEIND.NS       True
NUVAMA.NS        False
OBEROIRLTY.NS    False
PPLPHARMA.NS      True
Length: 206, dtype: bool

In [16]:
print()
print("Total buylist: ")
print(dfStats[buyList]["Close"].count())
print(dfStats[buyList]['Close'].index)
print()
print("Total SellList: ")
print(dfStats[sellList]["Close"].count())
print(dfStats[sellList]['Close'].index)

Total buylist:
44
Index(['BAJAJ-AUTO.NS', 'BEL.NS', 'COALINDIA.NS', 'EICHERMOT.NS',
       'GLENMARK.NS', 'HINDALCO.NS', 'MCX.NS', 'NATIONALUM.NS', 'NTPC.NS',
       'ONGC.NS', 'POLYCAB.NS', 'POWERGRID.NS', 'POWERINDIA.NS', 'SBIN.NS',
       'SHRIRAMFIN.NS', 'SUNPHARMA.NS', 'VEDL.NS', 'ABB.NS', 'ADANIENSOL.NS',
       'APLAPOLLO.NS', 'ASHOKLEY.NS', 'CUMMINSIND.NS', 'FEDERALBNK.NS',
       'HINDZINC.NS', 'KEI.NS', 'LUPIN.NS', 'MOTHERSON.NS', 'OIL.NS',
       'SAIL.NS', 'UNIONBANK.NS', 'BHARATFORG.NS', 'BIOCON.NS', 'DIVISLAB.NS',
       'INDIANB.NS', 'JINDALSTEL.NS', 'JSWSTEEL.NS', 'LAURUSLABS.NS',
       'MFSL.NS', 'NMDC.NS', 'SIEMENS.NS', 'TORNTPHARM.NS', 'INDUSTOWER.NS',
       'TORNTPOWER.NS', 'VOLTAS.NS'],
      dtype='object', name='Ticker')

Total SellList:
42
Index(['DIXON.NS', 'INFY.NS', 'ITC.NS', 'PGEL.NS', 'TCS.NS', 'TMPV.NS',
       'ADANIENT.NS', 'DLF.NS', 'HAVELLS.NS', 'KAYNES.NS', 'MANKIND.NS',
       'PERSISTENT.NS', 'RECLTD.NS', 'SUZLON.NS', 'TRENT.NS', 'WIPRO.NS',
       'IRFC.NS', 'JUBLFOOD.NS', 'KPITTECH.NS', 'RVNL.NS', 'SHREECEM.NS',
       'SWIGGY.NS', 'TATAELXSI.NS', 'VBL.NS', 'BAJAJHLDNG.NS', 'CROMPTON.NS',
       'INOXWIND.NS', 'IREDA.NS', 'JSWENERGY.NS', 'LICHSGFIN.NS', 'LODHA.NS',
       'LTM.NS', 'NAUKRI.NS', 'OFSS.NS', 'PAGEIND.NS', 'PIIND.NS',
       'PREMIERENE.NS', 'SRF.NS', 'SYNGENE.NS', 'TATATECH.NS', 'EXIDEIND.NS',
       'PPLPHARMA.NS'],
      dtype='object', name='Ticker')

In [17]:
rm = ['sharpe6M', 'FIP6M']
print(rm)

['sharpe6M', 'FIP6M']

In [18]:
#All Stocks which are not in BUY and SELL list
pd.set_option('display.max_rows', 300)  # or 1000
dfStats.loc[~(sellList ^ buyList)].dropna().sort_index()

,roc1M,roc3M,roc6M,roc12M,volatility6M,volatility12M,sharpe6MRoC,sharpe6M,FIP6M,sharpe12MRoC,sharpe12M,FIP12M,Beta,Close,ema100d
Ticker,,,,,,,,,,,,,,,
360ONE.NS,-6.21,-13.02,1.60,5.51,26.50,35.55,0.06,-0.32,-7,0.15,0.51,-4,1.39,1035.10,1120.54
ABCAPITAL.NS,-5.85,-9.34,10.93,65.16,26.01,31.43,0.42,1.02,-2,2.07,2.50,8,1.35,324.30,335.17
ADANIGREEN.NS,-9.84,-15.86,-16.82,-5.17,45.17,40.61,-0.37,-0.39,-16,-0.13,0.29,-4,1.83,854.15,970.09
ADANIPORTS.NS,-6.55,-3.30,1.27,17.40,27.39,26.68,0.05,0.29,-5,0.65,0.99,1,1.46,1421.30,1471.31
ALKEM.NS,-3.18,-0.05,1.46,7.76,20.52,22.00,0.07,0.30,0,0.35,0.92,14,0.80,5460.00,5538.46
AMBER.NS,-8.32,14.46,-9.62,18.76,35.03,38.89,-0.27,-0.28,4,0.48,0.53,12,1.44,7310.50,7108.56
AMBUJACEM.NS,-9.68,-18.77,-20.70,-15.95,22.06,21.93,-0.94,-1.91,-4,-0.73,-0.25,3,0.97,451.95,535.96
ANGELONE.NS,-6.11,-5.76,3.58,-3.64,36.56,41.64,0.10,0.16,-2,-0.09,0.43,6,1.74,218.96,250.42
APOLLOHOSP.NS,-0.54,10.60,5.13,11.79,16.77,19.69,0.31,-0.06,-12,0.60,1.33,-14,0.73,7779.00,7376.81
ASIANPAINT.NS,-6.54,-19.81,-5.35,-7.46,23.53,20.75,-0.23,-1.11,-10,-0.36,0.03,-2,0.60,2220.80,2553.68
ASTRAL.NS,-3.72,15.66,17.64,19.71,26.87,28.46,0.66,0.98,-1,0.69,0.94,2,1.02,1605.90,1506.09
AUBANK.NS,-2.79,-6.32,27.38,37.46,27.19,29.73,1.01,2.20,2,1.26,2.04,6,0.72,931.65,940.96
AUROPHARMA.NS,2.20,5.44,15.08,1.86,26.20,28.61,0.58,1.13,-9,0.07,0.65,-6,1.00,1247.30,1173.87
AXISBANK.NS,-6.91,1.49,13.85,8.81,21.76,22.18,0.64,1.73,12,0.40,1.12,-2,1.17,1288.30,1285.76
BAJAJFINSV.NS,-7.62,-9.73,-8.22,-5.60,21.04,22.55,-0.39,-0.89,-4,-0.25,0.12,0,1.22,1841.50,2013.61
BAJFINANCE.NS,-5.81,-4.94,-6.09,9.31,25.94,26.08,-0.23,-0.14,-1,0.36,0.61,10,1.14,938.05,983.48
BANDHANBNK.NS,-4.32,19.41,7.34,6.09,32.53,32.68,0.23,0.44,-7,0.19,0.70,3,1.31,174.12,160.32
BANKBARODA.NS,-10.53,-2.65,11.41,19.22,25.73,26.33,0.44,1.66,10,0.73,1.60,21,0.99,288.05,290.01
BANKINDIA.NS,-14.06,5.17,22.59,36.15,32.55,31.33,0.69,1.74,22,1.15,1.81,34,1.20,151.29,151.49
BDL.NS,5.56,-8.61,-10.24,-12.34,39.59,41.84,-0.26,-0.32,-6,-0.29,0.60,-14,1.24,1335.50,1418.14
BHARTIARTL.NS,-0.67,-11.35,-0.62,0.95,17.83,19.09,-0.03,-0.20,-2,0.05,0.86,0,0.84,1866.70,2001.23
BHEL.NS,-3.60,-11.15,7.11,12.83,33.87,32.93,0.21,0.84,20,0.39,1.06,30,1.42,255.40,262.84
BLUESTARCO.NS,-3.41,8.34,-0.31,10.42,26.22,30.41,-0.01,0.08,-6,0.34,-0.19,-17,0.85,1875.10,1853.18
BOSCHLTD.NS,-13.25,-12.32,-17.16,8.74,25.24,25.70,-0.68,-1.94,-22,0.34,0.84,5,0.95,31600.00,36312.99
BPCL.NS,-14.08,-11.33,2.33,13.79,26.29,25.98,0.09,0.78,-4,0.53,1.38,-1,1.05,331.15,354.00
BRITANNIA.NS,-1.87,-2.34,-1.69,9.71,17.44,19.30,-0.10,-0.71,-12,0.50,1.32,16,0.46,5890.00,5940.97
BSE.NS,2.28,5.19,35.72,31.04,38.49,47.96,0.93,1.52,0,0.65,1.80,11,1.61,2768.90,2706.02
CAMS.NS,-4.21,-11.96,-12.90,-15.56,26.10,31.31,-0.49,-1.16,-15,-0.50,0.11,-9,1.46,649.10,730.71
CANBK.NS,-11.09,-9.68,13.10,48.72,25.94,27.31,0.51,1.91,11,1.78,2.25,21,0.91,139.91,144.38
CDSL.NS,-4.85,-16.15,-17.01,-7.55,29.40,35.25,-0.58,-1.51,-18,-0.21,0.46,-10,1.62,1210.50,1421.51
CGPOWER.NS,-3.81,7.90,-5.65,11.53,31.56,32.63,-0.18,-0.61,-24,0.35,0.66,-11,1.38,697.55,673.37
CHOLAFIN.NS,-8.54,-6.93,-1.65,6.21,28.05,30.40,-0.06,0.56,-6,0.20,0.52,-17,1.31,1583.00,1677.95
CIPLA.NS,-1.72,-12.33,-11.86,-13.61,18.89,20.08,-0.63,-1.70,4,-0.68,-0.35,20,0.82,1325.00,1424.27
COFORGE.NS,-1.46,-29.57,-26.22,-19.27,32.03,34.81,-0.82,-2.50,-8,-0.55,-0.54,10,1.44,1168.50,1584.02
COLPAL.NS,-4.36,3.88,-1.92,-14.85,18.08,21.45,-0.11,-0.89,-8,-0.69,-0.38,0,0.61,2156.30,2176.71
CONCOR.NS,-4.42,-9.15,-8.84,-10.58,20.43,25.56,-0.43,-1.29,-8,-0.41,-0.13,2,1.15,473.75,511.14
DABUR.NS,-9.99,-7.33,-4.51,-2.85,19.06,20.63,-0.24,-1.52,-13,-0.14,-0.10,7,0.66,466.70,507.75
DALBHARAT.NS,-7.67,-13.64,-17.22,-4.87,22.43,23.76,-0.77,-2.36,-27,-0.20,0.54,-19,0.78,1840.20,2095.95
DELHIVERY.NS,-4.10,2.92,-7.64,36.03,30.80,33.17,-0.25,-0.68,4,1.09,1.72,24,0.64,415.65,423.49
DMART.NS,3.08,4.86,-11.38,-5.56,19.63,22.95,-0.58,-1.44,-2,-0.24,0.54,-1,0.69,3966.20,3935.52
DRREDDY.NS,0.05,1.23,5.17,9.40,20.00,20.87,0.26,-0.03,6,0.45,0.82,24,0.83,1287.00,1256.67
ETERNAL.NS,-6.80,-17.44,-29.47,-1.27,32.29,34.68,-0.91,-1.91,-10,-0.04,0.54,1,1.32,229.56,282.74
FORTIS.NS,-6.81,-0.63,-9.42,28.29,27.16,27.73,-0.35,-0.59,-17,1.02,1.42,-4,0.87,878.45,906.92
GAIL.NS,-12.12,-10.77,-12.86,-18.29,23.52,26.05,-0.55,-1.23,-8,-0.70,0.11,-2,1.19,148.98,165.81
GMRAIRPORT.NS,-8.51,-11.78,5.58,5.60,28.90,27.39,0.19,0.53,-4,0.20,1.07,12,0.96,92.07,97.47
GODREJCP.NS,-11.27,-11.23,-6.61,-12.85,21.14,22.17,-0.31,-1.37,2,-0.58,0.35,-4,0.49,1080.30,1183.41
GODREJPROP.NS,-4.93,-17.90,-16.42,-23.87,34.99,35.60,-0.47,-0.96,0,-0.67,-0.35,6,1.92,1645.60,1906.73
GRASIM.NS,-4.24,-5.22,-2.75,-1.70,19.41,20.60,-0.14,-0.36,0,-0.08,0.70,-6,1.09,2681.20,2810.06
HAL.NS,1.96,-8.33,-15.24,-10.06,27.31,29.38,-0.56,-0.85,4,-0.34,0.72,10,0.90,3989.90,4325.55
HCLTECH.NS,-2.20,-15.70,-0.41,-11.31,22.41,24.54,-0.02,-0.46,4,-0.46,-0.28,-4,1.12,1358.60,1545.57
HDFCAMC.NS,-8.80,-7.90,-11.03,14.63,25.13,27.98,-0.44,-1.23,-7,0.52,1.20,3,1.40,2461.10,2663.15
HDFCBANK.NS,-5.30,-15.18,-11.60,-11.47,13.47,15.41,-0.86,-2.10,-24,-0.74,0.14,-10,0.94,840.70,945.51
HDFCLIFE.NS,-8.60,-12.82,-13.58,-11.85,18.63,20.07,-0.73,-1.79,-16,-0.59,0.34,-12,0.84,653.75,735.81
HEROMOTOCO.NS,-4.03,-3.19,2.09,48.18,22.90,25.54,0.09,0.59,4,1.89,1.97,24,1.02,5480.00,5511.89
HINDPETRO.NS,-12.35,-22.94,-12.37,5.29,31.09,30.17,-0.40,-0.00,-3,0.18,0.83,9,1.12,384.55,443.38
HINDUNILVR.NS,-6.14,-5.24,-12.03,-4.57,18.36,18.68,-0.66,-1.83,-12,-0.24,0.06,-1,0.47,2194.60,2375.48
HUDCO.NS,-6.75,-23.21,-21.35,-20.46,32.52,33.82,-0.66,-1.16,-8,-0.60,0.17,-4,1.55,174.14,206.74
ICICIBANK.NS,-7.29,-4.80,-5.16,-9.72,17.02,17.37,-0.30,-1.04,-16,-0.56,0.43,-12,0.89,1278.40,1382.65
ICICIGI.NS,-0.62,-3.69,0.32,1.41,20.73,23.56,0.02,0.23,6,0.06,0.61,16,0.84,1889.70,1916.27
ICICIPRULI.NS,-8.09,-9.98,1.07,-1.95,19.17,21.85,0.06,0.15,2,-0.09,0.58,7,0.91,601.55,639.77
IDEA.NS,-6.42,-7.90,21.89,39.19,53.72,54.65,0.41,1.39,-5,0.72,0.85,-16,1.39,9.91,10.37
IDFCFIRSTB.NS,-9.15,-22.02,-4.31,3.22,33.50,31.69,-0.13,-0.33,-6,0.10,0.72,-5,0.92,66.76,78.94
IEX.NS,-4.28,-9.32,-12.56,-35.57,33.15,44.10,-0.38,-0.86,-13,-0.81,-0.36,1,1.16,120.26,134.09
INDHOTEL.NS,-8.30,-17.21,-15.08,-22.12,21.82,26.86,-0.69,-2.12,2,-0.82,-0.58,6,1.37,611.70,700.80
INDIGO.NS,-12.23,-16.26,-24.27,-19.16,28.69,28.40,-0.85,-1.96,-4,-0.67,-0.17,2,1.28,4236.70,5087.00
INDUSINDBK.NS,-7.90,1.97,19.80,5.10,24.24,39.66,0.82,1.52,3,0.13,0.16,-3,0.69,881.20,878.78
IOC.NS,-14.00,-3.15,10.93,23.14,23.94,22.90,0.46,1.36,10,1.01,1.61,21,0.86,161.22,163.73
JIOFIN.NS,-9.06,-21.26,-20.79,-10.68,23.64,26.37,-0.88,-2.22,-14,-0.41,0.52,-6,1.55,232.25,279.06
KALYANKJIL.NS,-5.15,-19.85,-14.37,-24.47,39.56,39.07,-0.36,-1.18,-18,-0.63,0.08,-3,1.32,389.00,450.73
KFINTECH.NS,-4.86,-15.87,-13.45,-23.48,29.34,37.72,-0.46,-1.24,-18,-0.62,0.23,-14,1.44,910.25,1039.03
KOTAKBANK.NS,-6.95,-12.24,-3.06,-12.41,18.77,21.12,-0.16,-0.14,-14,-0.59,0.14,-14,0.97,386.35,420.69
LICI.NS,-5.18,-5.79,-10.55,2.55,20.86,22.49,-0.51,-0.75,-6,0.11,0.48,4,0.89,805.40,860.74
LT.NS,-10.20,-5.91,5.00,16.07,21.09,22.03,0.24,0.91,8,0.73,1.03,2,1.22,3842.10,3995.05
LTF.NS,-6.25,-15.75,6.79,64.75,31.73,30.85,0.21,1.01,2,2.10,2.34,20,1.43,266.20,283.11
M&M.NS,-6.18,-14.06,-6.99,9.71,20.95,24.15,-0.33,-1.09,-4,0.40,0.85,-7,1.20,3187.60,3523.12
MANAPPURAM.NS,-9.32,-16.61,-8.21,12.11,30.64,30.10,-0.27,-0.58,-9,0.40,0.94,-5,1.02,256.85,289.54
MARICO.NS,-1.35,3.65,11.56,10.60,16.67,18.19,0.69,0.81,-4,0.58,1.54,6,0.59,778.00,750.65
MARUTI.NS,-9.08,-19.10,-15.73,11.40,19.81,20.69,-0.79,-1.06,-4,0.55,0.91,0,0.85,13508.00,15341.58
MAXHEALTH.NS,-4.62,-0.34,-6.57,-5.05,25.26,29.85,-0.26,-0.89,-4,-0.17,0.42,7,0.91,1041.50,1078.44
MAZDOCK.NS,7.29,-3.85,-13.10,-21.45,32.31,41.00,-0.41,-0.81,-14,-0.52,0.31,-8,1.38,2387.00,2505.39
MPHASIS.NS,-4.74,-21.62,-17.59,-9.62,25.54,29.59,-0.69,-2.23,0,-0.33,0.10,-10,1.28,2187.70,2649.22
MUTHOOTFIN.NS,-3.33,-14.95,5.36,49.40,36.44,35.77,0.15,0.86,14,1.38,1.34,18,0.77,3241.90,3533.01
NBCC.NS,-8.88,-30.57,-20.90,-10.72,33.93,35.70,-0.62,-1.30,-24,-0.30,0.40,-24,1.61,84.44,103.91
NESTLEIND.NS,-4.33,-3.53,7.77,4.49,17.24,18.96,0.45,0.30,-2,0.24,0.66,8,0.70,1235.80,1265.67
NHPC.NS,-3.04,-6.14,-13.86,-12.80,22.43,24.86,-0.62,-0.82,-16,-0.51,0.07,-10,1.00,73.04,77.74
NUVAMA.NS,-2.93,-18.38,0.54,9.15,32.45,38.56,0.02,0.16,-7,0.24,0.61,-8,1.28,1208.40,1351.06
NYKAA.NS,-5.94,-5.83,7.45,28.47,28.36,27.86,0.26,0.50,0,1.02,1.72,22,1.03,249.70,254.45
OBEROIRLTY.NS,-3.50,-11.92,-6.88,-10.04,25.60,28.77,-0.27,-0.56,-4,-0.35,0.03,-8,1.44,1469.50,1597.27
PATANJALI.NS,-3.34,-9.98,-14.46,-22.39,21.62,23.19,-0.67,-1.77,4,-0.97,-0.63,0,0.79,491.05,541.64
PAYTM.NS,-5.43,-20.03,-7.57,20.12,32.48,37.01,-0.23,-0.88,-10,0.54,1.42,4,1.25,1038.70,1200.98
PETRONET.NS,-13.87,-1.95,2.48,-8.02,27.65,25.55,0.09,0.32,0,-0.31,0.28,-8,1.04,278.55,287.12
PFC.NS,-5.07,11.61,-2.32,-0.27,26.06,28.09,-0.09,0.15,-2,-0.01,0.28,-12,1.46,392.80,384.96
PHOENIXLTD.NS,-4.84,-14.84,1.47,-5.02,21.64,28.96,0.07,0.34,1,-0.17,0.23,-5,1.09,1578.40,1720.13
PIDILITIND.NS,-7.08,-6.48,-5.56,-7.98,16.92,16.55,-0.33,-1.20,-8,-0.48,0.22,-2,0.64,1386.40,1474.65
PNB.NS,-11.10,-6.89,1.99,18.16,26.13,26.11,0.08,0.65,4,0.70,1.27,26,1.07,115.07,121.43
PNBHOUSING.NS,-8.40,-20.60,-12.52,-24.83,30.46,35.36,-0.41,-0.34,0,-0.70,0.08,6,1.30,755.50,881.21
POLICYBZR.NS,-3.48,-21.67,-15.98,-12.02,35.26,39.58,-0.45,-1.13,-11,-0.30,0.25,-5,1.20,1430.00,1660.40
PRESTIGE.NS,-6.35,-18.20,-13.61,-5.02,28.29,33.44,-0.48,-1.16,-8,-0.15,0.62,-2,1.70,1304.60,1541.64
RBLBANK.NS,-6.83,-5.67,7.45,49.22,29.13,34.64,0.26,0.84,-6,1.42,2.00,4,0.99,297.90,303.70
RELIANCE.NS,2.16,-9.32,4.40,1.76,18.70,19.91,0.24,0.41,3,0.09,0.84,7,1.13,1424.00,1450.93
SAMMAANCAP.NS,-5.59,-2.82,-12.02,17.40,41.13,45.76,-0.29,0.37,0,0.38,0.76,-12,1.10,141.53,148.05
SBICARD.NS,-6.93,-16.36,-17.82,-17.50,23.04,25.47,-0.77,-1.41,-8,-0.69,-0.50,2,1.09,720.70,819.47
SBILIFE.NS,-5.99,-5.88,6.96,8.46,16.92,19.45,0.41,0.75,4,0.43,1.67,12,0.84,1912.50,1988.97
SOLARINDS.NS,10.91,22.24,12.39,13.77,31.57,31.04,0.39,0.63,-3,0.44,1.56,9,0.91,14977.00,13469.67
SONACOMS.NS,-6.32,4.78,22.00,4.75,29.46,33.25,0.75,1.08,-4,0.14,0.11,-13,1.35,500.70,493.06
SUPREMEIND.NS,-4.01,13.77,-9.31,8.72,25.66,28.78,-0.36,-0.91,-20,0.30,0.67,-20,1.12,3815.60,3749.04
TATACONSUM.NS,-3.37,-7.51,-2.37,-4.73,20.32,21.14,-0.12,0.08,-4,-0.22,0.82,3,0.79,1102.50,1151.03
TATAPOWER.NS,-1.23,-1.77,-4.05,-2.42,19.92,22.36,-0.20,-0.32,-6,-0.11,0.40,4,1.22,372.90,377.71
TATASTEEL.NS,-10.04,6.07,13.18,39.54,27.21,28.79,0.48,1.05,0,1.37,1.06,10,1.47,191.01,186.64
TECHM.NS,-1.58,-16.00,-3.57,-8.52,24.63,25.08,-0.14,-0.88,10,-0.34,-0.19,8,0.94,1336.30,1529.18
TIINDIA.NS,-5.26,-0.13,-15.69,-9.88,33.29,33.42,-0.47,-1.12,-12,-0.30,0.05,-16,1.18,2608.60,2656.92
TITAN.NS,-3.89,2.66,23.53,23.43,18.40,19.67,1.28,1.77,-2,1.19,1.77,8,0.66,4159.20,4007.71
TVSMOTOR.NS,-6.25,-2.47,5.50,35.77,20.55,22.95,0.27,0.43,2,1.56,2.25,24,1.09,3627.80,3644.04
ULTRACEMCO.NS,-10.25,-3.45,-6.91,-1.64,18.57,18.77,-0.37,-0.86,-4,-0.09,0.56,6,0.87,11378.00,12285.32
UNITDSPR.NS,-1.81,-5.66,2.84,-12.39,20.94,21.20,0.14,0.33,13,-0.58,0.28,16,0.63,1355.80,1379.83
UNOMINDA.NS,-8.95,-15.78,-16.62,21.28,30.95,32.98,-0.54,-0.98,-7,0.65,0.90,-5,1.19,1082.10,1210.51
UPL.NS,-1.95,-21.40,-4.70,-5.85,32.70,30.58,-0.14,-0.56,5,-0.19,0.24,9,1.04,625.00,717.65
WAAREEENER.NS,-4.07,-12.44,-21.87,-0.16,39.24,47.01,-0.56,-1.72,-12,-0.00,0.65,-10,1.30,2599.00,2949.36
YESBANK.NS,-5.16,-9.03,-7.53,10.89,24.43,29.40,-0.31,-0.43,-6,0.37,0.75,-5,0.85,19.65,21.44
ZYDUSLIFE.NS,-1.39,-0.60,-7.44,3.49,19.06,21.55,-0.39,-1.41,-12,0.16,0.24,21,0.83,908.85,922.29

In [19]:
stocksBuy = dfStats[buyList].sort_values(rm[0], ascending = False)
stocksBuy

,roc1M,roc3M,roc6M,roc12M,volatility6M,volatility12M,sharpe6MRoC,sharpe6M,FIP6M,sharpe12MRoC,sharpe12M,FIP12M,Beta,Close,ema100d
Ticker,,,,,,,,,,,,,,,
BHARATFORG.NS,-2.56,26.80,53.78,69.63,26.48,31.79,2.03,3.51,18,2.19,1.96,18,1.45,1862.30,1525.98
SHRIRAMFIN.NS,-8.54,-0.90,61.21,63.10,29.06,32.91,2.11,3.51,18,1.92,1.61,10,1.73,987.20,928.89
NATIONALUM.NS,9.45,25.03,86.51,157.95,40.49,38.22,2.14,3.45,24,4.13,2.24,24,1.43,388.10,313.03
VEDL.NS,-1.25,17.37,52.30,78.24,33.21,31.65,1.57,3.19,28,2.47,1.89,48,1.34,709.40,613.73
MCX.NS,5.48,15.71,65.28,111.08,38.58,38.82,1.69,3.06,18,2.86,2.97,34,1.64,2577.10,2191.99
SBIN.NS,-8.59,11.84,25.91,42.09,21.47,19.88,1.21,2.89,18,2.12,2.31,29,0.90,1098.50,1039.26
FEDERALBNK.NS,-8.85,2.32,41.66,39.80,26.02,24.54,1.60,2.75,18,1.62,1.91,11,0.72,273.30,263.50
ASHOKLEY.NS,-11.44,4.33,31.92,70.02,27.79,27.88,1.15,2.70,20,2.51,2.40,24,1.08,186.94,178.74
APLAPOLLO.NS,-6.12,9.61,24.42,29.97,20.66,24.35,1.18,2.32,20,1.23,1.73,43,1.00,2097.90,1970.78
TORNTPHARM.NS,0.93,14.38,22.22,32.81,19.37,20.51,1.15,2.30,12,1.60,1.91,17,0.58,4373.70,3929.14
UNIONBANK.NS,-11.47,16.45,29.28,47.18,29.10,32.18,1.01,2.23,20,1.47,1.70,26,1.08,179.06,167.86
HINDALCO.NS,2.23,6.61,24.07,52.45,27.29,27.21,0.88,1.97,24,1.93,1.35,32,1.29,945.35,879.64
INDUSTOWER.NS,-3.62,4.72,27.88,7.42,25.20,27.85,1.11,1.91,4,0.27,1.18,6,0.91,438.50,424.72
INDIANB.NS,-9.25,7.36,19.74,62.93,32.11,29.58,0.61,1.82,18,2.13,2.21,24,1.02,898.90,852.65
ONGC.NS,-3.18,15.31,18.57,16.78,24.06,23.44,0.77,1.80,8,0.72,1.19,8,0.89,270.80,249.61
LUPIN.NS,0.05,9.18,20.50,10.59,18.31,23.85,1.12,1.76,10,0.44,0.73,23,0.86,2303.10,2140.67
NTPC.NS,-1.48,15.03,12.30,8.92,19.17,19.26,0.64,1.65,14,0.46,0.94,3,0.90,376.25,347.43
OIL.NS,-2.04,13.42,17.25,18.57,29.41,29.79,0.59,1.60,2,0.62,1.16,18,0.83,474.05,441.51
SUNPHARMA.NS,4.05,5.78,14.10,-0.39,17.54,19.49,0.80,1.53,20,-0.02,0.75,28,0.65,1807.40,1707.99
BEL.NS,3.28,14.94,13.70,46.57,26.62,26.53,0.51,1.50,6,1.76,2.18,4,0.84,457.35,419.48
HINDZINC.NS,-4.77,-6.11,19.18,33.52,40.53,37.05,0.47,1.50,9,0.90,1.07,11,1.21,575.00,574.32
COALINDIA.NS,1.63,11.14,16.80,21.57,23.04,20.63,0.73,1.43,6,1.05,1.20,15,0.86,437.65,405.65
CUMMINSIND.NS,-4.23,6.27,20.02,64.30,25.56,26.72,0.78,1.38,6,2.41,2.08,14,1.03,4691.30,4313.17
POWERINDIA.NS,-1.57,37.41,39.77,73.22,46.78,46.10,0.85,1.37,17,1.59,1.74,23,0.90,25160.00,20590.00
ADANIENSOL.NS,-2.98,-4.47,12.51,9.09,38.30,35.53,0.33,1.31,7,0.26,0.97,10,1.67,981.40,964.81
KEI.NS,-5.73,7.51,18.04,56.52,29.14,32.61,0.62,1.29,12,1.73,1.60,18,1.08,4789.50,4355.60
MOTHERSON.NS,-11.52,-1.63,11.67,33.10,29.66,32.95,0.39,1.26,7,1.00,1.24,7,1.61,117.98,117.72
ABB.NS,-1.49,15.72,15.42,9.20,27.08,25.85,0.57,1.18,6,0.36,0.74,16,1.01,5982.50,5447.97
LAURUSLABS.NS,-5.09,-7.85,21.39,69.45,27.93,29.51,0.77,1.12,4,2.35,2.24,26,1.03,1021.00,997.31
POLYCAB.NS,-4.44,8.00,12.94,49.90,27.69,27.98,0.47,1.10,4,1.78,2.02,24,1.09,8228.50,7577.09
TORNTPOWER.NS,-8.78,10.48,18.44,-5.86,28.72,29.70,0.64,1.08,12,-0.20,0.39,4,1.20,1428.90,1373.41
SAIL.NS,-9.77,1.72,11.18,33.14,31.17,32.48,0.36,0.99,18,1.02,1.25,30,1.47,149.52,146.46
JINDALSTEL.NS,-8.05,8.57,7.55,27.99,26.28,28.18,0.29,0.88,8,0.99,1.00,16,1.42,1144.10,1100.30
JSWSTEEL.NS,-5.70,2.39,4.37,16.12,23.24,24.91,0.19,0.85,9,0.65,0.80,12,1.36,1192.60,1181.04
EICHERMOT.NS,-9.29,-0.64,3.72,32.21,22.24,21.27,0.17,0.79,2,1.51,1.97,18,0.93,7266.00,7261.62
BIOCON.NS,-0.03,-1.07,14.28,21.26,24.17,27.76,0.59,0.71,13,0.77,0.78,27,0.97,389.70,379.29
MFSL.NS,-5.83,2.14,8.36,30.85,22.94,23.10,0.36,0.67,2,1.34,2.31,28,0.64,1707.60,1690.43
NMDC.NS,-3.19,-1.97,6.79,27.60,27.87,29.05,0.24,0.67,3,0.95,1.06,22,1.26,79.13,77.31
POWERGRID.NS,-1.16,12.82,8.31,-0.85,21.82,22.02,0.38,0.65,6,-0.04,0.65,1,1.00,295.20,277.89
DIVISLAB.NS,-1.22,-0.98,11.26,4.47,23.61,25.26,0.48,0.56,1,0.18,0.70,7,0.76,6330.00,6311.96
BAJAJ-AUTO.NS,-5.91,0.43,8.12,19.81,18.04,22.08,0.45,0.43,4,0.90,1.34,20,1.08,9383.00,9364.41
SIEMENS.NS,-5.55,5.41,3.19,11.28,26.99,27.88,0.12,0.38,9,0.40,0.58,25,0.81,3228.90,3153.82
VOLTAS.NS,-7.99,5.53,6.13,16.86,27.92,28.45,0.22,0.36,5,0.59,0.26,11,1.01,1436.50,1422.89
GLENMARK.NS,-0.89,4.05,8.58,53.69,23.41,29.70,0.37,0.10,4,1.81,1.57,7,0.52,2117.60,1989.20

In [20]:
stocksSell = dfStats[sellList].sort_values(rm[0], ascending = True)
stocksSell

,roc1M,roc3M,roc6M,roc12M,volatility6M,volatility12M,sharpe6MRoC,sharpe6M,FIP6M,sharpe12MRoC,sharpe12M,FIP12M,Beta,Close,ema100d
Ticker,,,,,,,,,,,,,,,
LTM.NS,-3.25,NaN,NaN,NaN,29.87,29.87,NaN,-10.39,-8,NaN,-10.39,-8,0.48,4317.20,4553.52
INOXWIND.NS,-11.28,-33.83,-41.71,-51.64,30.16,35.74,-1.38,-3.94,-25,-1.44,-1.87,-25,1.78,81.74,118.12
PAGEIND.NS,-3.01,-13.28,-22.93,-30.73,19.98,22.67,-1.15,-3.55,-33,-1.36,-0.95,-27,0.99,31145.00,35959.92
DIXON.NS,-6.88,-18.99,-39.93,-40.38,34.35,35.49,-1.16,-3.50,-25,-1.14,-0.66,-7,1.40,9804.00,12526.33
SYNGENE.NS,-5.58,-38.76,-36.00,-37.00,28.71,29.70,-1.25,-3.50,-22,-1.25,-1.66,-10,0.96,398.65,551.53
KPITTECH.NS,-10.66,-41.11,-37.10,-44.65,34.55,35.15,-1.07,-3.43,-26,-1.27,-1.54,-38,1.51,688.90,1047.97
EXIDEIND.NS,-7.60,-14.72,-20.95,-11.72,20.32,23.56,-1.03,-3.10,-24,-0.50,-0.36,-14,1.16,308.90,353.03
SUZLON.NS,-7.15,-24.78,-28.03,-29.75,26.76,33.88,-1.05,-2.67,-22,-0.88,-0.72,-30,1.42,39.62,49.95
ITC.NS,-2.42,-22.48,-22.20,-25.28,21.26,18.26,-1.04,-2.66,-25,-1.38,-1.26,-24,0.50,306.00,351.22
SHREECEM.NS,-9.53,-11.23,-19.16,-20.22,18.15,19.15,-1.06,-2.56,-6,-1.06,-0.77,-13,0.77,23590.00,27090.45
NAUKRI.NS,-4.89,-26.41,-24.91,-30.29,26.28,29.42,-0.95,-2.49,-28,-1.03,-0.86,-30,1.33,979.30,1242.08
KAYNES.NS,-4.01,-7.75,-47.51,-35.59,51.14,47.66,-0.93,-2.39,-20,-0.75,-0.08,-16,1.64,3701.80,4502.36
TRENT.NS,-5.39,-13.78,-21.12,-28.61,27.81,35.20,-0.76,-2.37,-16,-0.81,-0.58,-22,1.44,3689.40,4226.88
JUBLFOOD.NS,-6.01,-12.52,-20.85,-31.58,24.10,25.35,-0.87,-2.36,-23,-1.25,-0.70,-25,0.86,488.65,552.98
CROMPTON.NS,-6.42,-4.34,-17.16,-27.82,24.31,25.41,-0.71,-2.16,-28,-1.09,-1.28,-40,0.89,241.30,264.27
DLF.NS,-4.79,-16.36,-19.36,-14.11,25.07,29.30,-0.77,-2.14,-10,-0.48,-0.24,-12,1.75,574.95,673.19
OFSS.NS,-3.17,-12.68,-18.88,-19.34,26.83,30.03,-0.70,-2.13,-20,-0.64,-0.02,-22,1.32,6712.50,7627.94
PREMIERENE.NS,-1.28,-14.31,-29.36,-26.46,35.40,36.14,-0.83,-2.11,-16,-0.73,-0.43,-14,1.33,721.65,840.84
PPLPHARMA.NS,-3.03,-12.08,-20.80,-28.22,25.80,28.84,-0.81,-2.11,-14,-0.98,-0.85,-14,1.04,151.40,172.03
PIIND.NS,-2.70,-6.18,-13.53,-16.33,20.82,23.96,-0.65,-1.97,-10,-0.68,-0.16,-6,0.82,3033.20,3294.85
TATATECH.NS,-3.31,-11.96,-15.44,-12.59,22.61,26.12,-0.68,-1.95,-14,-0.48,-0.40,-11,1.21,566.10,642.37
SWIGGY.NS,-0.17,-22.01,-28.77,-4.79,34.11,37.87,-0.84,-1.90,-20,-0.13,-0.29,-10,1.07,301.25,356.48
LODHA.NS,-10.06,-16.25,-21.74,-32.91,28.95,35.49,-0.75,-1.88,-15,-0.93,-0.36,-17,1.83,888.85,1080.28
TATAELXSI.NS,-4.64,-17.88,-17.66,-24.52,30.96,31.24,-0.57,-1.79,-22,-0.78,-0.61,-28,1.31,4303.70,5186.08
WIPRO.NS,-1.10,-22.56,-14.83,-13.92,24.33,24.65,-0.61,-1.75,-4,-0.56,-1.12,-2,0.87,198.75,232.86
IREDA.NS,-6.46,-18.26,-23.10,-31.55,27.86,33.78,-0.83,-1.71,-24,-0.93,-0.53,-35,1.66,114.35,135.24
TMPV.NS,-13.24,-9.62,NaN,NaN,25.30,25.30,NaN,-1.67,-15,NaN,-1.67,-15,1.01,332.00,366.67
BAJAJHLDNG.NS,-5.13,-9.52,-16.31,-13.79,27.76,31.62,-0.59,-1.66,-16,-0.44,-0.23,-15,1.23,10250.00,11380.04
IRFC.NS,-5.77,-21.71,-20.33,-20.95,28.23,29.38,-0.72,-1.65,-16,-0.71,-0.52,-24,1.26,97.57,116.40
TCS.NS,-4.17,-19.74,-10.58,-24.29,22.86,21.13,-0.46,-1.61,-8,-1.15,-1.43,-28,0.88,2527.40,2968.99
HAVELLS.NS,-4.70,-6.28,-11.09,-16.26,20.69,22.31,-0.54,-1.54,-10,-0.73,-0.31,-6,0.86,1331.40,1413.78
MANKIND.NS,-3.75,-1.51,-11.18,-12.22,23.97,26.35,-0.47,-1.47,-18,-0.46,-0.04,-14,0.75,2163.30,2214.41
SRF.NS,-0.38,-16.84,-9.44,-14.90,25.20,25.80,-0.37,-1.15,-10,-0.58,-0.42,-24,1.07,2552.40,2859.11
LICHSGFIN.NS,-6.98,-7.29,-11.47,-15.30,21.14,24.29,-0.54,-1.05,-2,-0.63,-0.04,-2,1.24,500.20,536.89
RVNL.NS,-12.69,-22.44,-18.38,-20.38,34.62,36.55,-0.53,-0.97,-28,-0.56,-0.34,-37,1.54,276.20,324.45
ADANIENT.NS,-7.52,-10.74,-20.22,-13.08,34.44,32.39,-0.59,-0.93,-17,-0.40,-0.18,-15,1.78,1999.20,2234.00
INFY.NS,1.15,-18.60,-7.40,-9.74,24.89,25.74,-0.30,-0.90,-7,-0.38,-0.78,-5,1.03,1315.00,1499.65
RECLTD.NS,-7.26,-7.97,-10.83,-19.39,24.99,28.08,-0.43,-0.87,-6,-0.69,-0.38,-16,1.65,324.40,357.47
PERSISTENT.NS,1.06,-23.47,-0.46,-9.55,30.84,33.05,-0.01,-0.65,-2,-0.29,-0.05,-8,1.36,4783.10,5720.68
JSWENERGY.NS,-1.81,-0.74,-9.79,0.33,27.27,29.79,-0.36,-0.51,-2,0.01,-0.02,-8,1.28,478.90,490.93
VBL.NS,-3.02,-10.64,-1.34,-16.03,26.83,28.29,-0.05,-0.49,-8,-0.57,-0.20,-22,0.97,437.75,467.64
PGEL.NS,-16.81,-9.20,3.99,-38.10,42.09,51.86,0.09,-0.22,-14,-0.73,-0.80,-36,1.91,522.35,592.68

In [21]:
outputBuy = stocksBuy.sort_values(rm[1], ascending = False)[:20].reset_index().rename(columns = {'index':'symbol'})
outputBuy

,Ticker,roc1M,roc3M,roc6M,roc12M,volatility6M,volatility12M,sharpe6MRoC,sharpe6M,FIP6M,sharpe12MRoC,sharpe12M,FIP12M,Beta,Close,ema100d
0,VEDL.NS,-1.25,17.37,52.30,78.24,33.21,31.65,1.57,3.19,28,2.47,1.89,48,1.34,709.40,613.73
1,NATIONALUM.NS,9.45,25.03,86.51,157.95,40.49,38.22,2.14,3.45,24,4.13,2.24,24,1.43,388.10,313.03
2,HINDALCO.NS,2.23,6.61,24.07,52.45,27.29,27.21,0.88,1.97,24,1.93,1.35,32,1.29,945.35,879.64
3,UNIONBANK.NS,-11.47,16.45,29.28,47.18,29.10,32.18,1.01,2.23,20,1.47,1.70,26,1.08,179.06,167.86
4,SUNPHARMA.NS,4.05,5.78,14.10,-0.39,17.54,19.49,0.80,1.53,20,-0.02,0.75,28,0.65,1807.40,1707.99
5,ASHOKLEY.NS,-11.44,4.33,31.92,70.02,27.79,27.88,1.15,2.70,20,2.51,2.40,24,1.08,186.94,178.74
6,APLAPOLLO.NS,-6.12,9.61,24.42,29.97,20.66,24.35,1.18,2.32,20,1.23,1.73,43,1.00,2097.90,1970.78
7,BHARATFORG.NS,-2.56,26.80,53.78,69.63,26.48,31.79,2.03,3.51,18,2.19,1.96,18,1.45,1862.30,1525.98
8,SHRIRAMFIN.NS,-8.54,-0.90,61.21,63.10,29.06,32.91,2.11,3.51,18,1.92,1.61,10,1.73,987.20,928.89
9,INDIANB.NS,-9.25,7.36,19.74,62.93,32.11,29.58,0.61,1.82,18,2.13,2.21,24,1.02,898.90,852.65
10,SAIL.NS,-9.77,1.72,11.18,33.14,31.17,32.48,0.36,0.99,18,1.02,1.25,30,1.47,149.52,146.46
11,MCX.NS,5.48,15.71,65.28,111.08,38.58,38.82,1.69,3.06,18,2.86,2.97,34,1.64,2577.10,2191.99
12,FEDERALBNK.NS,-8.85,2.32,41.66,39.80,26.02,24.54,1.60,2.75,18,1.62,1.91,11,0.72,273.30,263.50
13,SBIN.NS,-8.59,11.84,25.91,42.09,21.47,19.88,1.21,2.89,18,2.12,2.31,29,0.90,1098.50,1039.26
14,POWERINDIA.NS,-1.57,37.41,39.77,73.22,46.78,46.10,0.85,1.37,17,1.59,1.74,23,0.90,25160.00,20590.00
15,NTPC.NS,-1.48,15.03,12.30,8.92,19.17,19.26,0.64,1.65,14,0.46,0.94,3,0.90,376.25,347.43
16,BIOCON.NS,-0.03,-1.07,14.28,21.26,24.17,27.76,0.59,0.71,13,0.77,0.78,27,0.97,389.70,379.29
17,TORNTPHARM.NS,0.93,14.38,22.22,32.81,19.37,20.51,1.15,2.30,12,1.60,1.91,17,0.58,4373.70,3929.14
18,TORNTPOWER.NS,-8.78,10.48,18.44,-5.86,28.72,29.70,0.64,1.08,12,-0.20,0.39,4,1.20,1428.90,1373.41
19,KEI.NS,-5.73,7.51,18.04,56.52,29.14,32.61,0.62,1.29,12,1.73,1.60,18,1.08,4789.50,4355.60

In [22]:
outputSell = stocksSell.sort_values(rm[1], ascending = True)[:30].reset_index().rename(columns = {'index':'symbol'})
outputSell

,Ticker,roc1M,roc3M,roc6M,roc12M,volatility6M,volatility12M,sharpe6MRoC,sharpe6M,FIP6M,sharpe12MRoC,sharpe12M,FIP12M,Beta,Close,ema100d
0,PAGEIND.NS,-3.01,-13.28,-22.93,-30.73,19.98,22.67,-1.15,-3.55,-33,-1.36,-0.95,-27,0.99,31145.00,35959.92
1,RVNL.NS,-12.69,-22.44,-18.38,-20.38,34.62,36.55,-0.53,-0.97,-28,-0.56,-0.34,-37,1.54,276.20,324.45
2,CROMPTON.NS,-6.42,-4.34,-17.16,-27.82,24.31,25.41,-0.71,-2.16,-28,-1.09,-1.28,-40,0.89,241.30,264.27
3,NAUKRI.NS,-4.89,-26.41,-24.91,-30.29,26.28,29.42,-0.95,-2.49,-28,-1.03,-0.86,-30,1.33,979.30,1242.08
4,KPITTECH.NS,-10.66,-41.11,-37.10,-44.65,34.55,35.15,-1.07,-3.43,-26,-1.27,-1.54,-38,1.51,688.90,1047.97
5,ITC.NS,-2.42,-22.48,-22.20,-25.28,21.26,18.26,-1.04,-2.66,-25,-1.38,-1.26,-24,0.50,306.00,351.22
6,INOXWIND.NS,-11.28,-33.83,-41.71,-51.64,30.16,35.74,-1.38,-3.94,-25,-1.44,-1.87,-25,1.78,81.74,118.12
7,DIXON.NS,-6.88,-18.99,-39.93,-40.38,34.35,35.49,-1.16,-3.50,-25,-1.14,-0.66,-7,1.40,9804.00,12526.33
8,IREDA.NS,-6.46,-18.26,-23.10,-31.55,27.86,33.78,-0.83,-1.71,-24,-0.93,-0.53,-35,1.66,114.35,135.24
9,EXIDEIND.NS,-7.60,-14.72,-20.95,-11.72,20.32,23.56,-1.03,-3.10,-24,-0.50,-0.36,-14,1.16,308.90,353.03
10,JUBLFOOD.NS,-6.01,-12.52,-20.85,-31.58,24.10,25.35,-0.87,-2.36,-23,-1.25,-0.70,-25,0.86,488.65,552.98
11,SUZLON.NS,-7.15,-24.78,-28.03,-29.75,26.76,33.88,-1.05,-2.67,-22,-0.88,-0.72,-30,1.42,39.62,49.95
12,TATAELXSI.NS,-4.64,-17.88,-17.66,-24.52,30.96,31.24,-0.57,-1.79,-22,-0.78,-0.61,-28,1.31,4303.70,5186.08
13,SYNGENE.NS,-5.58,-38.76,-36.00,-37.00,28.71,29.70,-1.25,-3.50,-22,-1.25,-1.66,-10,0.96,398.65,551.53
14,KAYNES.NS,-4.01,-7.75,-47.51,-35.59,51.14,47.66,-0.93,-2.39,-20,-0.75,-0.08,-16,1.64,3701.80,4502.36
15,OFSS.NS,-3.17,-12.68,-18.88,-19.34,26.83,30.03,-0.70,-2.13,-20,-0.64,-0.02,-22,1.32,6712.50,7627.94
16,SWIGGY.NS,-0.17,-22.01,-28.77,-4.79,34.11,37.87,-0.84,-1.90,-20,-0.13,-0.29,-10,1.07,301.25,356.48
17,MANKIND.NS,-3.75,-1.51,-11.18,-12.22,23.97,26.35,-0.47,-1.47,-18,-0.46,-0.04,-14,0.75,2163.30,2214.41
18,ADANIENT.NS,-7.52,-10.74,-20.22,-13.08,34.44,32.39,-0.59,-0.93,-17,-0.40,-0.18,-15,1.78,1999.20,2234.00
19,BAJAJHLDNG.NS,-5.13,-9.52,-16.31,-13.79,27.76,31.62,-0.59,-1.66,-16,-0.44,-0.23,-15,1.23,10250.00,11380.04
20,TRENT.NS,-5.39,-13.78,-21.12,-28.61,27.81,35.20,-0.76,-2.37,-16,-0.81,-0.58,-22,1.44,3689.40,4226.88
21,PREMIERENE.NS,-1.28,-14.31,-29.36,-26.46,35.40,36.14,-0.83,-2.11,-16,-0.73,-0.43,-14,1.33,721.65,840.84
22,IRFC.NS,-5.77,-21.71,-20.33,-20.95,28.23,29.38,-0.72,-1.65,-16,-0.71,-0.52,-24,1.26,97.57,116.40
23,LODHA.NS,-10.06,-16.25,-21.74,-32.91,28.95,35.49,-0.75,-1.88,-15,-0.93,-0.36,-17,1.83,888.85,1080.28
24,TMPV.NS,-13.24,-9.62,NaN,NaN,25.30,25.30,NaN,-1.67,-15,NaN,-1.67,-15,1.01,332.00,366.67
25,TATATECH.NS,-3.31,-11.96,-15.44,-12.59,22.61,26.12,-0.68,-1.95,-14,-0.48,-0.40,-11,1.21,566.10,642.37
26,PGEL.NS,-16.81,-9.20,3.99,-38.10,42.09,51.86,0.09,-0.22,-14,-0.73,-0.80,-36,1.91,522.35,592.68
27,PPLPHARMA.NS,-3.03,-12.08,-20.80,-28.22,25.80,28.84,-0.81,-2.11,-14,-0.98,-0.85,-14,1.04,151.40,172.03
28,PIIND.NS,-2.70,-6.18,-13.53,-16.33,20.82,23.96,-0.65,-1.97,-10,-0.68,-0.16,-6,0.82,3033.20,3294.85
29,HAVELLS.NS,-4.70,-6.28,-11.09,-16.26,20.69,22.31,-0.54,-1.54,-10,-0.73,-0.31,-6,0.86,1331.40,1413.78