@auther: Mitul Patel --> https://github.com/mitul19
Import libraries

In [7]:
import pandas as pd
import time
from datetime import datetime, date, timedelta
import yfinance as yf

from utils import *  #Our local functions.

In [8]:
# Reload utils module to get the updated functions
import importlib
import utils
importlib.reload(utils)
from utils import *

In [9]:
df = pd.read_csv('./indices/fo.csv')
df.tail(5)

         Symbol
203      VOLTAS
204  WAAREEENER
205       WIPRO
206     YESBANK
207   ZYDUSLIFE

Select Dates for analysis

In [10]:
# Dates 
dates = dict()
dates['startDate'] = str(date.today() - timedelta(days=365))
dates['date6M'] = str(date.today() - timedelta(days=180))
dates['endDate'] = str(date.today() - timedelta(days=4))

print('Start Date: ', dates['startDate'])
print('6M Date: ', dates['date6M'])
print('End Date: ', dates['endDate'])

Start Date:  2025-08-04
6M Date:  2026-02-05
End Date:  2026-07-31

In [11]:
# Create Yahoo symbol
df['Yahoo_Symbol'] = df.Symbol + '.NS'
df = df.set_index('Yahoo_Symbol')
symbol = list(df.index)
symbol[1]

'ABB.NS'

In [12]:
# yf data
# yf data dowload in chunkns
CHUNK = 50
close = []
for k in range(0, len(symbol), CHUNK):
    print(k, end = ',', flush = True)
    _symlist = symbol[k:k+CHUNK]
    _x = yf.download(_symlist, start = dates['startDate'], progress = False, auto_adjust=True)['Close']
    close = _x if len(close) == 0 else pd.concat([close, _x], axis = 1)
    time.sleep(.5)
close

0,50,100,150,200,

Ticker,360ONE.NS,ABB.NS,ABCAPITAL.NS,ADANIENSOL.NS,ADANIENT.NS,ADANIGREEN.NS,ADANIPORTS.NS,ADANIPOWER.NS,ALKEM.NS,AMBER.NS,...,UNOMINDA.NS,UPL.NS,VBL.NS,VEDL.NS,VMM.NS,VOLTAS.NS,WAAREEENER.NS,WIPRO.NS,YESBANK.NS,ZYDUSLIFE.NS
Date,,,,,,,,,,,,,,,,,,,,,
2025-08-04,1040.635742,5062.076172,278.450012,799.549988,2362.543701,989.799988,1383.071167,116.800003,4855.308594,7960.0,...,1059.681152,704.876953,506.917877,409.284393,141.679993,1337.598022,3086.868408,237.149048,18.889999,957.989075
2025-08-05,1054.286621,5053.626953,282.000000,802.049988,2327.159424,971.750000,1352.400391,115.900002,4873.630859,7891.5,...,1100.587646,713.543091,506.419525,415.924774,146.619995,1312.875610,3054.386719,237.014114,18.860001,959.387878
2025-08-06,1045.383911,5066.549316,277.149994,791.099976,2299.271973,957.549988,1361.362549,113.489998,4824.111816,7628.0,...,1083.925781,698.538269,497.549011,417.916870,146.369995,1310.084351,3216.595459,231.279358,18.730000,931.862610
2025-08-07,1053.890991,5087.920898,278.149994,794.599976,2248.794678,936.700012,1339.753662,115.790001,4825.102539,7729.5,...,1104.578613,698.686890,501.037415,415.308136,144.550003,1305.099976,3161.126709,233.554001,18.770000,943.602051
2025-08-08,1031.535156,5001.543945,271.799988,790.150024,2177.126709,914.049988,1319.439331,115.379997,4725.902344,7354.5,...,1081.531250,682.146973,494.309723,409.284393,139.009995,1300.813599,3059.283936,230.402283,18.540001,935.309509
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-07-29,1161.300049,7310.500000,397.600006,1667.800049,3024.500000,1373.099976,1719.699951,209.520004,5672.500000,7411.5,...,1168.699951,609.150024,446.704590,264.500000,108.239998,1313.300049,2736.199951,183.610001,22.840000,1122.699951
2026-07-30,1142.900024,7291.500000,394.049988,1659.000000,3049.100098,1358.699951,1664.099976,208.970001,5816.500000,7401.0,...,1172.800049,602.549988,450.850006,267.500000,107.889999,1333.199951,2624.899902,186.330002,22.540001,1115.099976
2026-07-31,1135.300049,7284.500000,404.299988,1645.400024,3009.500000,1383.000000,1696.500000,211.309998,5751.500000,7440.5,...,1180.500000,604.299988,442.299988,264.250000,107.099998,1328.900024,2680.199951,183.649994,22.770000,1126.800049
2026-08-03,NaN,7601.000000,424.350006,1647.000000,3068.000000,1395.000000,1701.000000,213.649994,5707.000000,7400.0,...,1210.000000,620.000000,445.000000,267.250000,111.199997,1324.800049,2676.000000,188.660004,23.000000,1121.000000
2026-08-04,1165.099976,7756.000000,417.700012,1648.000000,3032.399902,1391.599976,1693.400024,210.410004,5657.500000,7415.5,...,1222.599976,582.700012,440.899994,268.250000,111.470001,1313.400024,2680.600098,187.729996,22.860001,1115.699951

In [13]:
# # Keep the data within the date range
# data12M = close[:endDate].copy()

# # At least 12 months of trading is required
# data12M.dropna(axis = 1, inplace = True)
# data12M

data12M = close[:dates['endDate']].copy()
data12M

Ticker,360ONE.NS,ABB.NS,ABCAPITAL.NS,ADANIENSOL.NS,ADANIENT.NS,ADANIGREEN.NS,ADANIPORTS.NS,ADANIPOWER.NS,ALKEM.NS,AMBER.NS,...,UNOMINDA.NS,UPL.NS,VBL.NS,VEDL.NS,VMM.NS,VOLTAS.NS,WAAREEENER.NS,WIPRO.NS,YESBANK.NS,ZYDUSLIFE.NS
Date,,,,,,,,,,,,,,,,,,,,,
2025-08-04,1040.635742,5062.076172,278.450012,799.549988,2362.543701,989.799988,1383.071167,116.800003,4855.308594,7960.0,...,1059.681152,704.876953,506.917877,409.284393,141.679993,1337.598022,3086.868408,237.149048,18.889999,957.989075
2025-08-05,1054.286621,5053.626953,282.000000,802.049988,2327.159424,971.750000,1352.400391,115.900002,4873.630859,7891.5,...,1100.587646,713.543091,506.419525,415.924774,146.619995,1312.875610,3054.386719,237.014114,18.860001,959.387878
2025-08-06,1045.383911,5066.549316,277.149994,791.099976,2299.271973,957.549988,1361.362549,113.489998,4824.111816,7628.0,...,1083.925781,698.538269,497.549011,417.916870,146.369995,1310.084351,3216.595459,231.279358,18.730000,931.862610
2025-08-07,1053.890991,5087.920898,278.149994,794.599976,2248.794678,936.700012,1339.753662,115.790001,4825.102539,7729.5,...,1104.578613,698.686890,501.037415,415.308136,144.550003,1305.099976,3161.126709,233.554001,18.770000,943.602051
2025-08-08,1031.535156,5001.543945,271.799988,790.150024,2177.126709,914.049988,1319.439331,115.379997,4725.902344,7354.5,...,1081.531250,682.146973,494.309723,409.284393,139.009995,1300.813599,3059.283936,230.402283,18.540001,935.309509
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-07-27,1132.699951,7327.500000,400.450012,1703.300049,3036.600098,1399.699951,1770.400024,213.960007,5613.000000,7280.5,...,1162.400024,608.500000,463.985413,264.649994,110.309998,1319.300049,2741.399902,178.529999,22.940001,1108.199951
2026-07-28,1128.300049,7243.500000,391.350006,1649.500000,3002.300049,1377.800049,1774.699951,208.250000,5651.500000,7209.0,...,1163.900024,599.650024,429.523651,259.350006,109.580002,1311.099976,2694.300049,181.119995,22.809999,1099.199951
2026-07-29,1161.300049,7310.500000,397.600006,1667.800049,3024.500000,1373.099976,1719.699951,209.520004,5672.500000,7411.5,...,1168.699951,609.150024,446.704590,264.500000,108.239998,1313.300049,2736.199951,183.610001,22.840000,1122.699951
2026-07-30,1142.900024,7291.500000,394.049988,1659.000000,3049.100098,1358.699951,1664.099976,208.970001,5816.500000,7401.0,...,1172.800049,602.549988,450.850006,267.500000,107.889999,1333.199951,2624.899902,186.330002,22.540001,1115.099976
2026-07-31,1135.300049,7284.500000,404.299988,1645.400024,3009.500000,1383.000000,1696.500000,211.309998,5751.500000,7440.5,...,1180.500000,604.299988,442.299988,264.250000,107.099998,1328.900024,2680.199951,183.649994,22.770000,1126.800049

In [14]:
# Get month end prices
dfMonthEnd = getMonthlyPrices(data12M)
dfMonthEnd

Ticker,360ONE.NS,ABB.NS,ABCAPITAL.NS,ADANIENSOL.NS,ADANIENT.NS,ADANIGREEN.NS,ADANIPORTS.NS,ADANIPOWER.NS,ALKEM.NS,AMBER.NS,...,UNOMINDA.NS,UPL.NS,VBL.NS,VEDL.NS,VMM.NS,VOLTAS.NS,WAAREEENER.NS,WIPRO.NS,YESBANK.NS,ZYDUSLIFE.NS
Date,,,,,,,,,,,,,,,,,,,,,
2025-08-29,1007.101868,4978.637695,277.850006,764.150024,2243.696777,913.500000,1307.290527,120.129997,5261.087891,7267.5,...,1276.087158,708.888123,485.538818,413.740173,149.410004,1369.697144,3400.092773,240.387512,19.100000,980.169189
2025-09-30,1012.938171,5162.187012,292.350006,872.250000,2504.780029,1026.849976,1397.609863,144.649994,5381.616211,8089.0,...,1295.842041,649.512817,442.232544,458.148529,149.009995,1349.261353,3326.533936,230.710693,21.250000,981.018433
2025-10-31,1074.462769,5198.737793,324.200012,986.200012,2479.891113,1140.000000,1445.408447,157.850006,5462.464355,8036.5,...,1232.386841,713.196411,468.096680,485.442688,144.690002,1379.267090,3427.399902,231.963669,22.740000,973.575134
2025-11-28,1176.371216,5153.920898,358.049988,994.549988,2279.180908,1048.199951,1510.533936,147.490005,5639.536621,7181.0,...,1303.823975,751.376831,479.957336,517.359680,135.800003,1371.989990,3172.500000,240.503159,22.930000,941.653809
2025-12-31,1183.131958,5148.941406,357.700012,1027.349976,2238.698975,1015.099976,1463.631592,142.990005,5462.464355,6387.0,...,1282.871704,787.526917,488.229889,594.471863,136.369995,1356.937134,2968.100098,253.755753,21.600000,913.529053
2026-01-30,1127.753540,5555.777344,339.799988,894.799988,2019.497070,852.299988,1413.841431,135.380005,5632.096680,5716.0,...,1179.607422,697.201233,469.691406,670.354492,125.949997,1323.741577,2787.500000,234.224960,21.410000,884.505127
2026-02-27,1097.230591,6048.263184,344.450012,1011.549988,2160.833984,947.349976,1514.616699,140.110001,5639.500000,7974.0,...,1186.660767,631.289307,449.907074,706.599243,117.779999,1556.410645,2709.300049,198.690811,20.719999,920.872498
2026-03-30,944.119385,5917.298828,292.250000,934.900024,1758.014038,806.900024,1307.091309,150.429993,5299.000000,6549.0,...,1030.003540,562.505066,382.829681,654.799988,105.300003,1268.814087,3109.800049,185.521210,17.250000,870.417847
2026-04-30,1034.650024,7230.000000,345.500000,1342.250000,2407.323486,1227.150024,1650.344727,221.850006,5400.000000,8024.0,...,1110.778320,635.696594,513.130920,271.549988,122.290001,1425.920532,3118.800049,198.384293,19.930000,891.099243
2026-05-29,1104.500000,7253.000000,363.299988,1513.300049,2936.087158,1475.400024,1797.026489,243.369995,5498.000000,7615.0,...,1101.699951,638.618286,527.415100,352.600006,121.769997,1241.798828,3140.800049,201.943649,23.150000,1076.732422
2026-06-30,1074.599976,7031.000000,391.950012,1491.400024,3036.000000,1492.199951,1810.199951,223.770004,5570.000000,7530.0,...,1087.800049,565.723938,506.987732,280.750000,117.949997,1277.599976,2947.000000,168.465988,24.180000,1111.601074
2026-07-31,1135.300049,7284.500000,404.299988,1645.400024,3009.500000,1383.000000,1696.500000,211.309998,5751.500000,7440.5,...,1180.500000,604.299988,442.299988,264.250000,107.099998,1328.900024,2680.199951,183.649994,22.770000,1126.800049

In [15]:
# Stats DataFrame
dfStats = pd.DataFrame()

# Rate of change
dfStats['roc1M'] = getNMonthRoC(dfMonthEnd, 1)
dfStats['roc3M'] = getNMonthRoC(dfMonthEnd, 3)
dfStats['roc6M'] = getNMonthRoC(dfMonthEnd, 6)
dfStats['roc12M'] = getNMonthRoC(dfMonthEnd, 11)
dfStats
# dfStats = dfStats.reset_index()
# print(dfStats)
# dfStats = dfStats.set_index("Ticker")
# print(dfStats)

               roc1M  roc3M  roc6M  roc12M
Ticker
360ONE.NS       5.65   9.73   0.67   12.73
ABB.NS          3.61   0.75  31.12   46.32
ABCAPITAL.NS    3.15  17.02  18.98   45.51
ADANIENSOL.NS  10.33  22.59  83.88  115.32
ADANIENT.NS    -0.87  25.01  49.02   34.13
...              ...    ...    ...     ...
VOLTAS.NS       4.02  -6.80   0.39   -2.98
WAAREEENER.NS  -9.05 -14.06  -3.85  -21.17
WIPRO.NS        9.01  -7.43 -21.59  -23.60
YESBANK.NS     -5.83  14.25   6.35   19.21
ZYDUSLIFE.NS    1.37  26.45  27.39   14.96

[208 rows x 4 columns]

In [16]:

# Data for the past 6 months
# midDate = str(date.today() - timedelta(days=180))

data6M = data12M[dates['date6M']:].copy()
data6M

Ticker,360ONE.NS,ABB.NS,ABCAPITAL.NS,ADANIENSOL.NS,ADANIENT.NS,ADANIGREEN.NS,ADANIPORTS.NS,ADANIPOWER.NS,ALKEM.NS,AMBER.NS,...,UNOMINDA.NS,UPL.NS,VBL.NS,VEDL.NS,VMM.NS,VOLTAS.NS,WAAREEENER.NS,WIPRO.NS,YESBANK.NS,ZYDUSLIFE.NS
Date,,,,,,,,,,,,,,,,,,,,,
2026-02-05,1134.215942,5746.497070,344.649994,1011.450012,2235.600586,967.150024,1563.610229,153.449997,5617.216797,6399.5,...,1227.997070,740.482300,435.654358,644.437378,123.050003,1422.331787,3071.600098,230.754608,21.379999,904.187439
2026-02-06,1107.471191,5792.310059,347.750000,1017.700012,2225.404785,971.849976,1544.192017,152.740005,5638.544922,6640.0,...,1155.362793,734.193176,437.597900,660.026978,122.190002,1430.506104,3087.699951,228.114761,21.290001,887.352600
2026-02-09,1131.730347,5791.812012,352.899994,1032.500000,2249.094482,982.650024,1555.145874,151.369995,5704.513184,7048.0,...,1201.257935,736.916809,455.837402,668.584106,122.260002,1498.193481,3122.199951,227.481979,21.559999,922.620911
2026-02-10,1155.691284,5846.089844,353.750000,1016.750000,2227.404053,978.299988,1548.175293,149.050003,5765.025391,7510.5,...,1228.395996,738.848083,454.990173,678.813293,126.800003,1470.979004,3163.800049,228.856293,21.400000,886.503357
2026-02-11,1131.829834,5801.770996,344.250000,1033.800049,2233.401367,994.750000,1546.880737,150.910004,5842.897461,7696.0,...,1243.872070,741.819336,455.388885,689.632568,125.480003,1501.782227,3177.600098,227.215027,21.320000,897.493469
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-07-27,1132.699951,7327.500000,400.450012,1703.300049,3036.600098,1399.699951,1770.400024,213.960007,5613.000000,7280.5,...,1162.400024,608.500000,463.985413,264.649994,110.309998,1319.300049,2741.399902,178.529999,22.940001,1108.199951
2026-07-28,1128.300049,7243.500000,391.350006,1649.500000,3002.300049,1377.800049,1774.699951,208.250000,5651.500000,7209.0,...,1163.900024,599.650024,429.523651,259.350006,109.580002,1311.099976,2694.300049,181.119995,22.809999,1099.199951
2026-07-29,1161.300049,7310.500000,397.600006,1667.800049,3024.500000,1373.099976,1719.699951,209.520004,5672.500000,7411.5,...,1168.699951,609.150024,446.704590,264.500000,108.239998,1313.300049,2736.199951,183.610001,22.840000,1122.699951
2026-07-30,1142.900024,7291.500000,394.049988,1659.000000,3049.100098,1358.699951,1664.099976,208.970001,5816.500000,7401.0,...,1172.800049,602.549988,450.850006,267.500000,107.889999,1333.199951,2624.899902,186.330002,22.540001,1115.099976
2026-07-31,1135.300049,7284.500000,404.299988,1645.400024,3009.500000,1383.000000,1696.500000,211.309998,5751.500000,7440.5,...,1180.500000,604.299988,442.299988,264.250000,107.099998,1328.900024,2680.199951,183.649994,22.770000,1126.800049

In [17]:
# Volatility
dfStats['volatility6M'] = getVolatility(getDailyReturns(data6M))
dfStats['volatility12M'] = getVolatility(getDailyReturns(data12M))

# Sharpe using RoC, annualised returns and Frog in the pan
dfStats['sharpe6MRoC'] = getSharpeRoC(dfStats['roc6M'], dfStats['volatility6M'])
dfStats['sharpe6M'] = getSharpe(getDailyReturns(data6M))
dfStats['FIP6M'] = getFIP(data6M) 

dfStats['sharpe12MRoC'] = getSharpeRoC(dfStats['roc12M'], dfStats['volatility12M'])
dfStats['sharpe12M'] = getSharpe(getDailyReturns(data12M))
dfStats['FIP12M'] = getFIP(data12M)

# dfStats = dfStats.set_index("Ticker")
dfStats

,roc1M,roc3M,roc6M,roc12M,volatility6M,volatility12M,sharpe6MRoC,sharpe6M,FIP6M,sharpe12MRoC,sharpe12M,FIP12M
Ticker,,,,,,,,,,,,
360ONE.NS,5.65,9.73,0.67,12.73,29.89,28.23,0.02,0.16,-6,0.45,0.31,-5
ABB.NS,3.61,0.75,31.12,46.32,33.16,29.22,0.94,1.65,12,1.59,1.41,27
ABCAPITAL.NS,3.15,17.02,18.98,45.51,37.17,31.56,0.51,1.08,10,1.44,1.36,5
ADANIENSOL.NS,10.33,22.59,83.88,115.32,39.51,38.24,2.12,2.75,18,3.02,2.11,21
ADANIENT.NS,-0.87,25.01,49.02,34.13,35.40,34.80,1.38,1.92,8,0.98,0.88,-4
...,...,...,...,...,...,...,...,...,...,...,...,...
VOLTAS.NS,4.02,-6.80,0.39,-2.98,34.53,31.03,0.01,-0.24,0,-0.10,0.13,0
WAAREEENER.NS,-9.05,-14.06,-3.85,-21.17,36.50,39.33,-0.11,-0.59,4,-0.54,-0.17,-7
WIPRO.NS,9.01,-7.43,-21.59,-23.60,26.38,25.01,-0.82,-1.66,-8,-0.94,-0.91,-5
YESBANK.NS,-5.83,14.25,6.35,19.21,29.87,27.56,0.21,0.59,-2,0.70,0.83,4
ZYDUSLIFE.NS,1.37,26.45,27.39,14.96,25.01,22.02,1.10,1.95,4,0.68,0.86,7

In [18]:
# Get Nifty data
dfNifty = yf.download("^NSEI", start = dates['startDate'], progress = False, auto_adjust=True)['Close']
dfNifty = dfNifty.rename(columns = {'^NSEI':'Nifty'})
# dfNifty.reset_index()
dfNifty

Ticker             Nifty
Date
2025-08-04  24722.750000
2025-08-05  24649.550781
2025-08-06  24574.199219
2025-08-07  24596.150391
2025-08-08  24363.300781
...                  ...
2026-07-28  23985.349609
2026-07-29  24250.199219
2026-07-30  24317.150391
2026-07-31  24383.599609
2026-08-04  24469.000000

[245 rows x 1 columns]

In [19]:
# Get stock beta
dfStats['Beta'] = getBeta(dfNifty, data12M)

# close and ema
dfStats['Close'] = round(data12M.iloc[-1], 2)
dfStats['ema100d'] = round(data12M.ewm(span=100).mean().iloc[-1], 2)
dfStats

,roc1M,roc3M,roc6M,roc12M,volatility6M,volatility12M,sharpe6MRoC,sharpe6M,FIP6M,sharpe12MRoC,sharpe12M,FIP12M,Beta,Close,ema100d
Ticker,,,,,,,,,,,,,,,
360ONE.NS,5.65,9.73,0.67,12.73,29.89,28.23,0.02,0.16,-6,0.45,0.31,-5,1.42,1135.30,1096.26
ABB.NS,3.61,0.75,31.12,46.32,33.16,29.22,0.94,1.65,12,1.59,1.41,27,1.03,7284.50,6814.04
ABCAPITAL.NS,3.15,17.02,18.98,45.51,37.17,31.56,0.51,1.08,10,1.44,1.36,5,1.67,404.30,369.49
ADANIENSOL.NS,10.33,22.59,83.88,115.32,39.51,38.24,2.12,2.75,18,3.02,2.11,21,1.50,1645.40,1433.05
ADANIENT.NS,-0.87,25.01,49.02,34.13,35.40,34.80,1.38,1.92,8,0.98,0.88,-4,1.63,3009.50,2771.19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
VOLTAS.NS,4.02,-6.80,0.39,-2.98,34.53,31.03,0.01,-0.24,0,-0.10,0.13,0,1.19,1328.90,1333.42
WAAREEENER.NS,-9.05,-14.06,-3.85,-21.17,36.50,39.33,-0.11,-0.59,4,-0.54,-0.17,-7,0.88,2680.20,2963.25
WIPRO.NS,9.01,-7.43,-21.59,-23.60,26.38,25.01,-0.82,-1.66,-8,-0.94,-0.91,-5,0.74,183.65,189.56
YESBANK.NS,-5.83,14.25,6.35,19.21,29.87,27.56,0.21,0.59,-2,0.70,0.83,4,1.24,22.77,22.55
ZYDUSLIFE.NS,1.37,26.45,27.39,14.96,25.01,22.02,1.10,1.95,4,0.68,0.86,7,0.77,1126.80,1046.79

In [20]:
# Apply filters: for buy and sell condition creation
cond1 = dfStats['Close'] > dfStats['ema100d']
cond2 = dfStats['sharpe6M'] > 0 
cond3 = dfStats['FIP12M'] > 0
cond4 = dfStats['sharpe12M'] > 0
cond5 = dfStats['FIP6M'] > 0
buyList = cond1 & cond2 & cond3 & cond4 & cond5
print([i for i in range(len(buyList)) if buyList.iloc[i] == True])
print([elem for i,elem in enumerate(buyList) if buyList.iloc[i] == True])
buyList

[1, 2, 3, 8, 15, 18, 20, 23, 29, 30, 31, 32, 37, 38, 42, 50, 53, 54, 59, 61, 65, 66, 69, 70, 72, 88, 90, 93, 104, 108, 112, 119, 123, 137, 141, 142, 154, 157, 159, 161, 163, 164, 166, 174, 175, 176, 177, 179, 190, 192, 194, 196, 197, 207]
[True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True]

Ticker
360ONE.NS        False
ABB.NS            True
ABCAPITAL.NS      True
ADANIENSOL.NS     True
ADANIENT.NS      False
                 ...
VOLTAS.NS        False
WAAREEENER.NS    False
WIPRO.NS         False
YESBANK.NS       False
ZYDUSLIFE.NS      True
Length: 208, dtype: bool

In [21]:
sellcond1 = dfStats['Close'] < dfStats['ema100d']
sellcond2 = dfStats['sharpe6M'] < 0 
sellcond3 = dfStats['FIP12M'] < 0
sellcond4 = dfStats['sharpe12M'] < 0
sellcond5 = dfStats['FIP6M'] < 0
sellList = sellcond1 & sellcond2 & sellcond3 & sellcond4 & sellcond5
# sellList = sellcond1
print([i for i in range(len(sellList)) if sellList.iloc[i] == True])
print([elem for i,elem in enumerate(sellList) if sellList.iloc[i] == True])

sellList

[10, 45, 51, 52, 58, 76, 77, 81, 86, 95, 96, 98, 99, 100, 105, 111, 136, 147, 155, 167, 168, 184, 202, 205]
[True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True]

Ticker
360ONE.NS        False
ABB.NS           False
ABCAPITAL.NS     False
ADANIENSOL.NS    False
ADANIENT.NS      False
                 ...
VOLTAS.NS        False
WAAREEENER.NS    False
WIPRO.NS          True
YESBANK.NS       False
ZYDUSLIFE.NS     False
Length: 208, dtype: bool

In [22]:
print()
print("Total buylist: ")
print(dfStats[buyList]["Close"].count())
print(dfStats[buyList]['Close'].index)
print()
print("Total SellList: ")
print(dfStats[sellList]["Close"].count())
print(dfStats[sellList]['Close'].index)

Total buylist:
54
Index(['ABB.NS', 'ABCAPITAL.NS', 'ADANIENSOL.NS', 'ALKEM.NS', 'ASIANPAINT.NS',
       'AUROPHARMA.NS', 'BAJAJ-AUTO.NS', 'BAJFINANCE.NS', 'BHARATFORG.NS',
       'BHARTIARTL.NS', 'BHEL.NS', 'BIOCON.NS', 'BSE.NS', 'CAMS.NS',
       'CHOLAFIN.NS', 'CUMMINSIND.NS', 'DELHIVERY.NS', 'DIVISLAB.NS',
       'EICHERMOT.NS', 'FEDERALBNK.NS', 'GLENMARK.NS', 'GMRAIRPORT.NS',
       'GODREJPROP.NS', 'GRASIM.NS', 'HAL.NS', 'IDFCFIRSTB.NS', 'INDHOTEL.NS',
       'INDUSINDBK.NS', 'JSWSTEEL.NS', 'KEI.NS', 'LAURUSLABS.NS', 'LUPIN.NS',
       'MARICO.NS', 'NESTLEIND.NS', 'NYKAA.NS', 'OBEROIRLTY.NS',
       'PIDILITIND.NS', 'PNBHOUSING.NS', 'POLYCAB.NS', 'POWERINDIA.NS',
       'PRESTIGE.NS', 'RADICO.NS', 'RECLTD.NS', 'SHRIRAMFIN.NS', 'SIEMENS.NS',
       'SOLARINDS.NS', 'SONACOMS.NS', 'SUNPHARMA.NS', 'TITAN.NS',
       'TORNTPHARM.NS', 'TVSMOTOR.NS', 'UNIONBANK.NS', 'UNITDSPR.NS',
       'ZYDUSLIFE.NS'],
      dtype='object', name='Ticker')

Total SellList:
24
Index(['AMBUJACEM.NS', 'COCHINSHIP.NS', 'DABUR.NS', 'DALBHARAT.NS',
       'DRREDDY.NS', 'HDFCBANK.NS', 'HDFCLIFE.NS', 'HINDUNILVR.NS',
       'ICICIPRULI.NS', 'INFY.NS', 'INOXWIND.NS', 'IREDA.NS', 'IRFC.NS',
       'ITC.NS', 'JUBLFOOD.NS', 'KPITTECH.NS', 'NBCC.NS', 'PATANJALI.NS',
       'PIIND.NS', 'RELIANCE.NS', 'RVNL.NS', 'TATAELXSI.NS', 'VMM.NS',
       'WIPRO.NS'],
      dtype='object', name='Ticker')

In [23]:
rm = ['sharpe6M', 'FIP6M']
print(rm)

['sharpe6M', 'FIP6M']

In [24]:
#All Stocks which are not in BUY and SELL list
pd.set_option('display.max_rows', 300)  # or 1000
dfStats.loc[~(sellList ^ buyList)].dropna().sort_index()

,roc1M,roc3M,roc6M,roc12M,volatility6M,volatility12M,sharpe6MRoC,sharpe6M,FIP6M,sharpe12MRoC,sharpe12M,FIP12M,Beta,Close,ema100d
Ticker,,,,,,,,,,,,,,,
360ONE.NS,5.65,9.73,0.67,12.73,29.89,28.23,0.02,0.16,-6,0.45,0.31,-5,1.42,1135.30,1096.26
ADANIENT.NS,-0.87,25.01,49.02,34.13,35.40,34.80,1.38,1.92,8,0.98,0.88,-4,1.63,3009.50,2771.19
ADANIGREEN.NS,-7.32,12.70,62.27,51.40,42.20,42.78,1.48,1.97,12,1.20,1.01,-1,1.71,1383.00,1343.39
ADANIPORTS.NS,-6.28,2.80,19.99,29.77,29.47,27.41,0.68,0.72,-2,1.09,0.90,-1,1.39,1696.50,1710.31
ADANIPOWER.NS,-5.57,-4.75,56.09,75.90,36.52,43.15,1.54,2.00,2,1.76,1.61,-9,0.99,211.31,206.25
AMBER.NS,-1.19,-7.27,30.17,2.38,47.29,41.54,0.64,0.90,8,0.06,0.05,5,1.48,7440.50,7527.84
ANGELONE.NS,-9.61,-3.19,18.48,37.43,44.30,41.10,0.42,0.82,-14,0.91,0.56,-7,1.76,297.95,309.67
APLAPOLLO.NS,1.72,-4.49,-11.06,13.39,30.02,25.23,-0.37,-1.11,-4,0.53,0.69,21,1.13,1819.50,1873.59
APOLLOHOSP.NS,3.17,17.29,28.85,17.86,17.96,18.95,1.61,2.75,16,0.94,1.20,-5,0.59,8957.00,8299.13
ASHOKLEY.NS,5.38,4.27,-14.07,34.01,43.71,37.14,-0.32,-0.62,2,0.92,1.08,15,1.87,166.18,160.14
ASTRAL.NS,8.46,-5.30,-1.90,6.63,32.71,30.75,-0.06,-0.07,10,0.22,0.21,5,0.85,1448.60,1485.39
AUBANK.NS,1.09,3.19,6.72,46.00,33.25,29.43,0.20,0.55,-2,1.56,1.29,-1,1.22,1047.30,1002.12
AXISBANK.NS,-8.56,-2.98,-10.21,17.72,26.36,23.77,-0.39,-0.48,-8,0.75,0.72,7,1.22,1229.50,1293.17
BAJAJFINSV.NS,13.98,16.23,4.01,6.13,26.90,23.78,0.15,0.25,-6,0.26,0.33,-5,1.29,2029.10,1839.12
BAJAJHLDNG.NS,6.98,11.85,6.33,-9.63,28.78,28.75,0.22,0.52,11,-0.33,-0.52,-7,1.18,11343.00,10478.58
BANDHANBNK.NS,-14.72,-12.81,12.60,7.62,49.94,41.16,0.25,0.66,16,0.19,0.32,0,1.71,174.13,189.43
BANKBARODA.NS,-10.94,-4.94,-16.35,7.57,31.16,27.53,-0.52,-0.83,-8,0.27,0.28,4,1.32,242.60,261.62
BANKINDIA.NS,-1.75,1.85,-13.19,29.17,35.08,32.61,-0.38,-0.64,2,0.89,0.92,27,1.54,137.95,142.42
BDL.NS,-8.43,-8.14,-18.24,-12.37,37.78,38.96,-0.48,0.12,3,-0.32,-0.41,-12,1.46,1253.10,1313.88
BEL.NS,-5.82,-10.07,-13.25,5.44,24.73,25.25,-0.54,-0.76,-3,0.22,0.13,-5,0.87,387.85,416.25
BLUESTARCO.NS,3.76,-5.14,-7.01,-10.22,34.85,30.94,-0.20,-0.40,-1,-0.33,0.06,-6,1.11,1681.20,1688.10
BOSCHLTD.NS,2.97,14.14,12.47,2.82,31.97,27.83,0.39,1.01,7,0.10,0.15,-10,1.23,41085.00,38632.75
BPCL.NS,5.34,6.42,-9.80,8.89,34.60,29.24,-0.28,-0.89,-5,0.30,0.33,-15,1.30,319.75,312.41
BRITANNIA.NS,7.00,-3.83,-6.04,-5.45,20.56,20.38,-0.29,-0.54,12,-0.27,-0.15,5,0.63,5416.50,5375.11
CANBK.NS,-0.43,-4.12,-12.43,24.34,33.35,28.86,-0.37,-0.70,-4,0.84,0.78,14,1.40,124.98,129.94
CDSL.NS,3.04,5.75,1.89,-5.56,33.76,31.20,0.06,0.08,-2,-0.18,-0.33,-17,1.79,1333.00,1309.05
CGPOWER.NS,-9.32,6.15,47.83,24.63,34.41,33.00,1.39,1.72,10,0.75,0.99,-13,1.11,863.40,850.98
CIPLA.NS,0.53,13.55,12.31,-6.44,23.55,21.32,0.52,1.08,-4,-0.30,0.02,-2,0.63,1473.20,1390.61
COALINDIA.NS,-4.41,-12.83,-3.52,16.53,23.74,22.53,-0.15,-0.02,-2,0.73,0.93,19,0.21,414.15,432.80
COFORGE.NS,17.69,44.24,4.30,0.50,45.75,39.06,0.09,0.57,-6,0.01,0.17,-5,1.16,1717.00,1443.62
COLPAL.NS,3.91,0.21,-0.64,-8.94,28.08,24.19,-0.02,0.09,0,-0.37,-0.13,-11,0.85,2076.10,2060.76
CONCOR.NS,10.57,3.27,5.33,0.83,31.35,26.25,0.17,0.24,2,0.03,-0.21,0,1.17,523.90,485.35
CROMPTON.NS,-4.16,-3.32,18.91,-20.20,33.88,28.09,0.56,0.57,-6,-0.72,-0.65,-35,1.23,260.20,261.94
DIXON.NS,17.86,25.81,34.49,-15.79,43.99,39.35,0.78,1.21,-8,-0.40,-0.30,-18,1.61,14049.00,12371.86
DLF.NS,7.67,13.73,5.01,-9.67,34.75,29.35,0.14,0.23,2,-0.33,-0.45,-5,1.72,659.30,618.87
DMART.NS,-10.49,-14.50,6.27,-17.55,27.44,24.38,0.23,0.11,6,-0.72,-0.16,7,0.57,3921.00,4109.68
ETERNAL.NS,14.30,22.43,10.54,-3.66,36.42,33.29,0.29,0.48,-13,-0.11,0.14,-7,1.42,302.45,269.19
FORCEMOT.NS,-3.65,-10.06,-6.74,-7.88,51.44,48.60,-0.13,-0.41,-8,-0.16,0.35,-7,1.94,17902.00,19031.78
FORTIS.NS,-1.14,2.50,11.10,3.79,25.41,25.70,0.44,0.93,2,0.15,0.50,-6,0.82,945.00,940.44
GAIL.NS,4.60,11.16,11.84,8.10,27.95,24.76,0.42,1.06,0,0.33,0.41,-11,1.14,181.44,167.79
GODFRYPHLP.NS,-1.83,-5.22,4.81,-41.51,53.25,53.69,0.09,0.54,-4,-0.77,-0.36,-19,1.29,2133.40,2210.53
GODREJCP.NS,5.98,0.81,-6.79,-12.67,26.87,23.83,-0.25,-0.52,3,-0.53,-0.46,6,0.84,1070.40,1065.41
GVT&D.NS,-12.55,-3.20,33.84,55.56,47.02,43.58,0.72,1.15,2,1.27,1.26,-1,1.02,4323.30,4390.42
HAVELLS.NS,8.75,2.13,-1.40,-16.70,26.04,23.53,-0.05,-0.38,6,-0.71,-0.62,-7,1.05,1260.70,1232.20
HCLTECH.NS,26.95,13.47,-18.22,-3.22,34.49,28.01,-0.53,-0.72,-4,-0.11,-0.03,9,0.82,1346.90,1236.65
HDFCAMC.NS,-1.41,-1.46,6.25,-2.14,36.98,31.38,0.17,-0.00,6,-0.07,-0.04,0,1.56,2615.80,2609.94
HEROMOTOCO.NS,13.99,7.18,0.68,9.51,28.51,26.40,0.02,-0.11,6,0.36,0.92,15,1.22,5386.00,5030.73
HINDALCO.NS,2.40,-5.63,1.76,39.15,29.99,27.86,0.06,0.47,16,1.41,1.46,37,0.79,974.45,979.83
HINDPETRO.NS,-1.19,4.06,-8.72,4.76,41.70,35.01,-0.21,-0.61,4,0.14,0.14,-2,1.56,389.75,394.91
HINDZINC.NS,1.13,-9.52,-12.64,30.96,34.88,36.86,-0.36,-0.46,-12,0.84,0.92,-2,1.08,539.20,560.49
HYUNDAI.NS,14.44,19.98,-0.71,-11.37,31.65,30.34,-0.02,0.21,-6,-0.37,0.17,-7,0.83,2180.70,1975.72
ICICIBANK.NS,4.38,13.61,5.93,2.69,21.70,18.72,0.27,0.37,6,0.14,0.03,-11,0.94,1423.40,1344.01
ICICIGI.NS,-6.77,-7.56,-10.16,-11.11,27.11,24.05,-0.37,-0.93,-2,-0.46,-0.50,1,0.70,1623.70,1772.19
IDEA.NS,-10.03,27.30,16.47,100.46,37.59,48.64,0.44,0.99,-3,2.07,1.59,3,1.39,13.01,12.74
IEX.NS,5.68,7.30,7.22,-2.76,31.60,31.61,0.23,0.64,8,-0.09,0.20,0,1.27,132.24,124.94
INDIANB.NS,2.43,0.29,-6.29,30.81,35.55,32.69,-0.18,0.01,-20,0.94,1.07,-1,1.44,836.50,837.75
INDIGO.NS,-3.68,20.39,12.50,-8.41,40.07,33.85,0.31,0.49,-3,-0.25,-0.14,-4,1.84,5171.00,4903.54
INDUSTOWER.NS,-0.15,-4.60,-11.97,15.51,25.06,25.55,-0.48,-0.89,-8,0.61,0.62,-1,0.90,391.10,410.12
IOC.NS,0.57,-1.46,-13.05,7.08,30.49,25.76,-0.43,-1.30,0,0.27,0.32,12,1.12,140.17,144.10
JINDALSTEL.NS,3.99,-9.87,-2.61,16.56,29.91,28.04,-0.09,-0.31,0,0.59,0.57,11,1.18,1102.40,1120.62
JIOFIN.NS,8.47,4.10,0.77,-17.72,31.56,27.53,0.02,-0.18,-1,-0.64,-0.83,-14,1.59,256.46,244.36
JSWENERGY.NS,-4.89,-0.82,21.04,13.94,31.65,29.37,0.66,1.21,-2,0.47,0.27,-5,0.95,554.65,544.33
KALYANKJIL.NS,58.42,48.42,69.39,21.87,57.64,48.19,1.20,2.03,-4,0.45,0.30,-18,1.63,612.60,442.38
KAYNES.NS,21.87,-5.93,9.47,-37.86,56.38,53.54,0.17,0.48,2,-0.71,-0.68,-13,1.68,3804.60,3559.71
KFINTECH.NS,8.05,6.13,-6.25,-6.91,38.46,33.93,-0.16,-0.04,-2,-0.20,-0.31,-17,1.42,937.90,897.13
KOTAKBANK.NS,-0.33,2.00,-4.17,-0.28,24.51,20.77,-0.17,-0.25,12,-0.01,-0.00,-1,1.06,390.30,389.47
LICHSGFIN.NS,-7.25,-5.70,-0.61,-5.78,28.84,24.76,-0.02,0.25,2,-0.23,-0.31,-5,1.07,523.10,543.35
LICI.NS,-1.61,8.95,5.43,2.01,28.28,23.53,0.19,0.39,-14,0.09,-0.01,-15,1.09,424.70,413.67
LODHA.NS,30.22,38.54,28.04,4.33,43.59,36.06,0.64,1.03,8,0.12,0.19,-6,1.81,1243.95,1017.13
LT.NS,-4.94,-0.91,1.15,10.45,31.40,24.73,0.04,0.02,6,0.42,0.50,7,1.41,3938.90,3943.84
LTF.NS,0.16,12.41,9.81,44.80,38.52,34.39,0.25,0.75,-6,1.30,1.45,5,1.75,311.25,292.63
LTM.NS,23.29,3.54,-26.01,-13.55,36.89,31.09,-0.71,-1.23,0,-0.44,-0.29,3,1.08,4362.10,4235.86
M&M.NS,11.91,10.87,0.07,7.34,32.65,28.23,0.00,-0.09,-4,0.26,0.40,0,1.49,3398.50,3168.94
MANAPPURAM.NS,14.70,26.53,31.06,42.95,34.78,32.55,0.89,1.58,6,1.32,1.25,-2,1.23,371.85,316.49
MANKIND.NS,-2.99,9.92,16.27,-0.07,28.67,25.68,0.57,1.37,-3,-0.00,-0.14,-18,0.76,2469.60,2397.19
MARUTI.NS,0.84,6.91,-2.50,-3.77,27.66,24.78,-0.09,-0.28,8,-0.15,0.70,19,1.11,14234.00,13775.57
MAXHEALTH.NS,-2.55,10.82,15.01,-4.66,26.38,25.95,0.57,0.57,8,-0.18,-0.37,-3,0.74,1098.50,1059.33
MAZDOCK.NS,-4.60,-12.86,-7.14,-7.93,37.47,33.92,-0.19,0.16,4,-0.23,-0.26,-7,1.55,2381.80,2445.06
MCX.NS,-5.11,-9.40,6.50,82.15,35.68,37.39,0.18,0.82,4,2.20,1.62,15,1.01,2692.20,2764.49
MFSL.NS,-5.37,-5.47,-7.10,-6.44,29.49,25.86,-0.24,-0.74,-10,-0.25,0.17,-7,0.96,1499.00,1610.19
MOTHERSON.NS,1.96,24.59,34.17,63.32,38.94,33.99,0.88,1.39,0,1.86,1.46,0,1.69,150.75,136.23
MOTILALOFS.NS,-10.44,6.46,13.06,0.18,40.19,39.10,0.32,0.71,-10,0.00,-0.00,-29,1.84,851.95,875.10
MPHASIS.NS,11.26,5.64,-12.83,-13.73,32.43,29.51,-0.40,-0.46,0,-0.47,-0.31,1,0.95,2342.30,2289.84
MUTHOOTFIN.NS,4.08,-8.90,-17.85,19.27,40.24,36.83,-0.44,-0.46,-8,0.52,0.64,1,1.39,3119.60,3212.66
NAM-INDIA.NS,-0.05,16.25,33.71,51.16,44.02,38.42,0.77,1.34,2,1.33,1.19,-3,1.84,1161.40,1073.95
NATIONALUM.NS,3.08,-11.90,-7.59,96.51,40.48,39.57,-0.19,0.09,15,2.44,1.93,40,0.59,350.05,365.66
NAUKRI.NS,25.77,26.44,-1.33,-9.07,34.13,29.70,-0.04,0.50,-2,-0.31,-0.21,-23,0.79,1226.25,1084.83
NHPC.NS,-3.20,-5.37,2.50,3.78,25.35,24.05,0.10,0.14,-8,0.16,-0.03,-19,0.79,78.73,78.42
NMDC.NS,-0.14,-5.90,7.90,27.36,28.43,27.56,0.28,0.40,0,0.99,0.92,6,0.91,85.04,85.18
NTPC.NS,-2.64,-13.00,-1.72,8.81,20.14,18.90,-0.09,-0.39,-5,0.47,0.48,2,0.50,347.25,362.19
OFSS.NS,3.81,18.30,48.28,40.89,37.16,33.01,1.30,2.61,12,1.24,1.12,-5,0.83,11186.00,9724.01
OIL.NS,9.99,-6.56,-8.71,20.71,33.31,30.80,-0.26,-0.26,2,0.67,0.46,9,-0.20,458.60,450.44
ONGC.NS,3.25,-19.04,-7.70,9.39,24.77,23.40,-0.31,-0.56,10,0.40,0.49,13,0.03,242.53,257.33
PAGEIND.NS,-2.41,10.19,23.29,-7.95,26.30,23.83,0.89,1.15,1,-0.33,-0.44,-25,0.76,40375.00,38482.21
PAYTM.NS,17.65,22.56,18.07,11.27,40.57,36.84,0.45,0.73,-12,0.31,0.79,-13,1.66,1343.00,1189.65
PERSISTENT.NS,28.70,16.01,-7.73,5.33,40.04,34.72,-0.19,-0.17,7,0.15,0.40,10,0.95,5549.00,5094.27
PETRONET.NS,-0.02,2.61,-1.99,8.09,35.66,29.45,-0.06,-0.12,4,0.27,0.26,-5,1.29,280.75,275.77
PFC.NS,0.95,-4.48,14.93,15.99,29.25,26.76,0.51,0.50,4,0.60,0.40,-1,1.17,424.35,415.93
PGEL.NS,14.99,14.86,11.99,15.10,48.39,50.83,0.25,0.45,12,0.30,-0.24,-7,1.99,613.35,549.81
PHOENIXLTD.NS,-2.84,7.27,13.32,26.15,30.75,27.10,0.43,0.77,-1,0.96,1.07,9,1.26,1893.30,1867.99
PNB.NS,5.64,6.06,-7.35,14.98,30.46,27.19,-0.24,-0.31,0,0.55,0.52,13,1.40,112.71,108.19
POLICYBZR.NS,-1.66,-3.88,-3.20,-9.56,30.59,33.03,-0.10,0.36,4,-0.29,-0.11,-2,0.80,1601.50,1609.48
POWERGRID.NS,-0.72,-10.71,12.06,6.19,19.43,19.74,0.62,0.03,8,0.31,0.20,12,0.43,284.25,290.07
PREMIERENE.NS,-2.74,0.47,42.10,2.90,32.37,33.61,1.30,1.84,18,0.09,0.18,-1,0.81,1022.20,1004.37
RBLBANK.NS,1.75,11.57,25.69,44.37,32.44,30.86,0.79,1.50,6,1.44,1.31,-1,1.19,375.50,346.96
SAIL.NS,-2.57,-8.44,11.84,44.23,38.30,34.49,0.31,0.54,-4,1.28,1.09,15,1.05,169.03,170.98
SBICARD.NS,11.29,2.52,-12.09,-17.55,28.99,26.15,-0.42,-0.74,-3,-0.67,-0.63,-12,1.25,660.15,653.77
SBILIFE.NS,6.59,3.46,-5.70,4.38,23.72,19.82,-0.24,-0.48,2,0.22,0.25,11,0.83,1882.00,1852.43
SBIN.NS,0.05,-2.11,-2.90,30.33,27.76,22.77,-0.10,-0.06,5,1.33,1.34,29,1.07,1027.40,1021.99
SHREECEM.NS,3.46,7.97,-3.20,-10.51,25.54,21.36,-0.13,-0.21,0,-0.49,-0.64,-6,1.01,26055.00,25655.85
SRF.NS,-4.07,4.32,-6.70,-7.19,34.92,29.83,-0.19,-0.42,0,-0.24,-0.35,-5,1.18,2622.50,2706.01
SUPREMEIND.NS,9.74,-3.66,-0.67,-21.72,27.87,27.27,-0.02,-0.38,0,-0.80,-0.62,-25,0.82,3465.40,3509.19
SUZLON.NS,-18.49,-13.62,0.71,-14.92,37.22,32.51,0.02,0.20,-9,-0.46,-0.79,-28,1.30,48.01,52.57
SWIGGY.NS,19.01,5.39,-8.04,-30.48,42.46,38.32,-0.19,-0.38,-16,-0.80,-0.71,-31,1.19,284.86,275.50
TATACONSUM.NS,0.70,-4.57,-3.67,2.52,24.40,22.60,-0.15,-0.36,-2,0.11,0.19,0,0.57,1083.10,1119.83
TATAPOWER.NS,-1.25,-13.83,4.58,2.38,22.87,20.77,0.20,0.56,-11,0.11,0.05,-16,0.79,380.70,391.78
TATASTEEL.NS,0.87,-8.40,0.24,25.32,27.64,26.36,0.01,-0.02,4,0.96,0.88,13,1.15,189.69,193.35
TCS.NS,17.08,-2.55,-22.83,-20.13,32.15,27.00,-0.71,-1.23,-10,-0.75,-0.70,-13,0.84,2365.60,2327.03
TECHM.NS,20.61,14.98,-2.80,15.56,32.79,27.67,-0.09,0.35,-5,0.56,0.69,9,0.63,1651.30,1462.03
TIINDIA.NS,-9.12,-6.61,18.00,-6.96,34.96,34.06,0.51,1.04,8,-0.20,0.01,-13,1.20,2753.00,2907.67
TMPV.NS,-3.53,0.30,-2.14,-48.79,36.10,50.73,-0.06,-0.33,2,-0.96,-0.98,-21,1.54,339.75,353.09
TRENT.NS,-8.43,8.95,19.28,-43.18,37.78,47.01,0.51,0.68,-2,-0.92,-0.93,-19,1.32,3005.90,2947.43
ULTRACEMCO.NS,7.94,4.83,-4.32,-3.91,28.37,22.90,-0.15,-0.23,2,-0.17,0.07,1,1.28,11903.00,11434.16
UNOMINDA.NS,8.52,6.28,0.08,-7.49,35.22,32.93,0.00,-0.06,3,-0.23,0.50,0,1.34,1180.50,1131.22
UPL.NS,6.82,-4.94,-13.32,-14.75,36.57,31.23,-0.36,-0.96,-6,-0.47,-0.34,2,1.29,604.30,623.68
VBL.NS,-12.76,-13.80,-5.83,-8.91,32.92,29.75,-0.18,0.26,-2,-0.30,-0.32,-17,1.12,442.30,482.96
VEDL.NS,-5.88,-2.69,-60.58,-36.13,100.88,74.36,-0.60,-0.94,7,-0.49,0.03,30,1.21,264.25,384.81
VOLTAS.NS,4.02,-6.80,0.39,-2.98,34.53,31.03,0.01,-0.24,0,-0.10,0.13,0,1.19,1328.90,1333.42
WAAREEENER.NS,-9.05,-14.06,-3.85,-21.17,36.50,39.33,-0.11,-0.59,4,-0.54,-0.17,-7,0.88,2680.20,2963.25
YESBANK.NS,-5.83,14.25,6.35,19.21,29.87,27.56,0.21,0.59,-2,0.70,0.83,4,1.24,22.77,22.55

In [25]:
stocksBuy = dfStats[buyList].sort_values(rm[0], ascending = False)
stocksBuy

,roc1M,roc3M,roc6M,roc12M,volatility6M,volatility12M,sharpe6MRoC,sharpe6M,FIP6M,sharpe12MRoC,sharpe12M,FIP12M,Beta,Close,ema100d
Ticker,,,,,,,,,,,,,,,
LAURUSLABS.NS,19.69,65.13,88.39,112.34,32.15,29.13,2.75,4.26,25,3.86,2.76,28,0.88,1816.20,1371.32
RADICO.NS,10.26,27.09,53.83,52.51,33.02,32.94,1.63,3.01,8,1.59,1.56,10,0.74,4340.80,3611.82
ADANIENSOL.NS,10.33,22.59,83.88,115.32,39.51,38.24,2.12,2.75,18,3.02,2.11,21,1.50,1645.40,1433.05
SONACOMS.NS,24.12,27.07,55.65,74.73,32.42,30.57,1.72,2.64,22,2.44,2.01,19,1.24,769.40,614.87
POWERINDIA.NS,-7.86,-4.10,70.58,68.37,44.34,43.17,1.59,2.64,22,1.58,1.20,26,0.81,32175.00,31151.12
DIVISLAB.NS,22.96,24.40,33.68,31.93,21.73,22.93,1.55,2.61,14,1.39,1.02,10,0.60,8056.00,6751.24
BHARATFORG.NS,2.91,17.27,53.25,99.60,30.80,28.82,1.73,2.44,12,3.46,2.36,25,1.31,2199.80,1962.18
BHEL.NS,-1.40,15.86,55.43,96.29,38.85,36.10,1.43,2.43,14,2.67,1.66,31,1.14,407.00,369.23
AUROPHARMA.NS,0.10,13.72,30.84,53.73,26.97,25.84,1.14,2.37,14,2.08,1.64,4,0.45,1580.20,1453.11
TORNTPHARM.NS,10.88,22.65,30.48,45.18,24.35,21.40,1.25,2.36,18,2.11,1.81,22,0.28,5122.80,4526.50
SOLARINDS.NS,-1.57,19.19,36.51,33.40,32.86,32.16,1.11,2.18,24,1.04,0.96,12,0.91,18391.00,16916.92
NYKAA.NS,7.25,25.93,40.38,44.86,28.60,27.84,1.41,1.99,8,1.61,1.78,13,1.08,333.40,289.49
ZYDUSLIFE.NS,1.37,26.45,27.39,14.96,25.01,22.02,1.10,1.95,4,0.68,0.86,7,0.77,1126.80,1046.79
FEDERALBNK.NS,8.73,25.06,24.71,87.18,25.90,24.98,0.95,1.90,21,3.49,2.61,36,0.94,358.85,310.84
MARICO.NS,4.59,12.86,19.85,20.50,19.01,17.79,1.04,1.80,10,1.15,1.18,1,0.50,870.65,813.52
SUNPHARMA.NS,7.15,10.36,25.91,25.98,20.42,19.15,1.27,1.72,14,1.36,1.17,33,0.50,1990.50,1841.67
CUMMINSIND.NS,-1.67,5.67,35.93,46.10,32.59,27.97,1.10,1.70,20,1.65,1.78,29,0.88,5519.00,5286.91
ABB.NS,3.61,0.75,31.12,46.32,33.16,29.22,0.94,1.65,12,1.59,1.41,27,1.03,7284.50,6814.04
BAJAJ-AUTO.NS,18.57,16.90,21.73,35.35,26.78,22.83,0.81,1.62,10,1.55,1.70,13,0.84,11520.50,10098.28
NESTLEIND.NS,7.95,3.99,14.46,31.90,22.06,20.45,0.66,1.59,6,1.56,1.56,5,0.58,1509.60,1391.03
PNBHOUSING.NS,2.21,1.50,29.05,40.83,34.11,32.04,0.85,1.55,4,1.27,1.14,11,1.46,1053.10,1000.83
TITAN.NS,11.06,11.54,22.97,34.79,27.48,22.88,0.84,1.47,12,1.52,1.79,9,1.01,4875.20,4360.32
BSE.NS,-5.43,0.42,30.70,74.40,38.32,38.61,0.80,1.46,8,1.93,1.21,11,1.45,3646.20,3599.59
GODREJPROP.NS,13.35,15.29,34.19,8.63,36.87,34.92,0.93,1.45,13,0.25,0.20,11,1.92,2105.70,1879.52
POLYCAB.NS,-8.58,12.81,30.46,29.03,32.41,29.04,0.94,1.40,14,1.00,1.12,23,1.06,9106.50,8854.12
OBEROIRLTY.NS,3.42,9.72,22.87,14.02,26.95,25.92,0.85,1.34,6,0.54,0.60,7,1.25,1827.70,1722.49
BIOCON.NS,1.89,18.51,16.20,22.35,26.59,26.35,0.61,1.28,2,0.85,0.55,12,0.72,425.70,407.80
HAL.NS,6.06,7.09,1.42,8.14,27.37,26.73,0.05,1.27,10,0.30,0.27,7,0.96,4646.50,4378.46
ASIANPAINT.NS,4.23,13.36,14.12,10.20,24.47,23.83,0.58,1.23,10,0.43,0.65,9,1.00,2747.30,2604.61
BAJFINANCE.NS,13.58,22.54,23.48,30.80,33.98,30.30,0.69,1.23,12,1.02,1.02,24,1.53,1141.20,971.58
TVSMOTOR.NS,24.63,23.48,17.70,32.09,33.11,27.72,0.53,1.13,6,1.16,1.56,17,1.26,4313.10,3616.67
ABCAPITAL.NS,3.15,17.02,18.98,45.51,37.17,31.56,0.51,1.08,10,1.44,1.36,5,1.67,404.30,369.49
GLENMARK.NS,1.34,-7.16,10.81,16.40,30.07,26.96,0.36,1.02,11,0.61,0.42,9,0.84,2233.90,2205.47
UNITDSPR.NS,13.12,15.24,12.11,17.05,27.86,23.49,0.43,1.01,8,0.73,0.71,21,0.79,1515.90,1350.84
LUPIN.NS,0.56,5.52,12.99,28.37,21.02,20.51,0.62,1.01,4,1.38,1.38,9,0.61,2415.00,2325.86
SIEMENS.NS,4.96,-0.78,21.84,23.33,34.40,29.98,0.63,0.99,14,0.78,1.01,32,1.16,3760.00,3536.00
PIDILITIND.NS,1.90,17.98,13.41,6.42,25.05,20.83,0.54,0.95,12,0.31,0.57,10,1.03,1611.40,1506.09
KEI.NS,-7.89,2.91,24.32,31.34,34.90,31.21,0.70,0.87,2,1.00,0.98,11,1.22,4999.00,4970.10
INDUSINDBK.NS,9.55,10.70,13.17,37.13,33.70,29.04,0.39,0.81,15,1.28,0.96,13,1.46,1012.45,935.08
GRASIM.NS,0.03,10.96,10.00,11.72,24.38,21.49,0.41,0.80,4,0.55,0.63,9,1.09,3100.80,3014.93
EICHERMOT.NS,11.90,11.35,11.13,29.70,33.04,26.73,0.34,0.75,7,1.11,1.44,16,1.24,7833.50,7287.89
CAMS.NS,0.43,8.35,15.14,8.94,33.06,28.97,0.46,0.73,5,0.31,0.37,1,1.34,796.15,760.31
DELHIVERY.NS,2.10,3.19,13.95,2.97,30.68,30.03,0.45,0.70,2,0.10,0.30,11,1.05,481.95,464.18
INDHOTEL.NS,3.45,16.67,10.04,-2.19,27.89,24.78,0.36,0.69,18,-0.09,0.09,21,1.38,738.55,693.01
GMRAIRPORT.NS,-6.09,9.16,12.11,22.30,34.09,30.01,0.36,0.64,3,0.74,0.63,4,1.46,105.26,103.55
CHOLAFIN.NS,3.40,18.41,13.51,30.36,37.75,33.16,0.36,0.58,2,0.92,0.87,2,1.71,1849.90,1673.15
PRESTIGE.NS,3.30,14.27,10.59,3.60,37.25,32.47,0.28,0.50,8,0.11,0.13,1,1.72,1616.20,1516.91
SHRIRAMFIN.NS,1.00,12.30,3.20,82.51,41.98,35.17,0.08,0.50,13,2.35,1.70,32,1.98,1046.70,988.59
JSWSTEEL.NS,4.15,1.01,5.18,24.42,24.56,23.33,0.21,0.37,6,1.05,0.95,14,1.18,1270.00,1238.43
ALKEM.NS,3.26,6.51,2.12,9.32,25.33,22.27,0.08,0.32,10,0.42,0.89,11,0.73,5751.50,5511.93
RECLTD.NS,3.69,6.47,5.88,11.53,30.33,26.64,0.19,0.21,6,0.43,0.13,2,1.33,372.95,350.30
IDFCFIRSTB.NS,6.53,21.60,1.32,24.55,38.19,31.14,0.03,0.15,10,0.79,0.81,8,1.30,84.68,76.19
BHARTIARTL.NS,7.82,5.83,1.43,5.72,21.70,19.27,0.07,0.13,6,0.30,0.32,7,0.64,1972.00,1873.72
UNIONBANK.NS,2.24,6.24,-2.47,41.24,36.81,32.58,-0.07,0.13,3,1.27,1.14,18,1.51,171.24,166.85

In [26]:
stocksSell = dfStats[sellList].sort_values(rm[0], ascending = True)
stocksSell

,roc1M,roc3M,roc6M,roc12M,volatility6M,volatility12M,sharpe6MRoC,sharpe6M,FIP6M,sharpe12MRoC,sharpe12M,FIP12M,Beta,Close,ema100d
Ticker,,,,,,,,,,,,,,,
PATANJALI.NS,-13.73,-22.82,-28.87,-39.69,29.45,25.55,-0.98,-2.45,-4,-1.55,-2.06,-3,0.77,354.60,429.27
TATAELXSI.NS,-4.09,-9.47,-29.77,-28.57,34.05,31.63,-0.87,-2.07,-6,-0.90,-1.38,-21,1.09,3672.90,4058.41
HDFCLIFE.NS,-4.75,-6.21,-24.70,-28.70,25.94,21.90,-0.95,-2.02,-16,-1.31,-1.26,-23,0.88,548.50,598.68
KPITTECH.NS,-10.89,-21.16,-42.44,-49.62,46.19,39.04,-0.92,-1.88,-6,-1.27,-1.64,-23,0.99,598.40,713.53
RVNL.NS,-4.39,-24.25,-34.13,-25.25,34.17,34.14,-1.00,-1.87,-16,-0.74,-1.14,-43,1.51,225.48,256.44
WIPRO.NS,9.01,-7.43,-21.59,-23.60,26.38,25.01,-0.82,-1.66,-8,-0.94,-0.91,-5,0.74,183.65,189.56
HDFCBANK.NS,-6.24,-1.45,-18.16,-20.08,27.14,20.85,-0.67,-1.56,-26,-0.96,-1.21,-35,1.27,748.15,793.48
IRFC.NS,-1.52,-14.45,-24.98,-23.07,29.88,28.45,-0.84,-1.53,-13,-0.81,-1.13,-30,1.34,89.15,96.70
INFY.NS,12.96,-2.31,-29.64,-20.23,33.86,29.67,-0.88,-1.51,-22,-0.68,-0.65,-26,0.76,1130.10,1164.78
ICICIPRULI.NS,5.63,0.65,-18.79,-13.78,29.94,24.48,-0.63,-1.49,-6,-0.56,-0.57,-1,1.02,515.40,525.61
DALBHARAT.NS,5.83,-5.32,-12.61,-24.70,31.81,26.43,-0.40,-1.27,-6,-0.93,-0.83,-14,1.17,1799.70,1827.22
INOXWIND.NS,-13.29,-22.60,-27.61,-43.43,44.41,37.44,-0.62,-1.25,-20,-1.16,-1.64,-38,1.83,78.14,90.28
DABUR.NS,1.12,-3.30,-15.73,-17.64,26.51,23.43,-0.59,-1.17,-1,-0.75,-0.80,-15,0.99,421.45,440.43
AMBUJACEM.NS,2.45,-2.22,-14.86,-22.88,32.23,26.89,-0.46,-1.16,-10,-0.85,-1.12,-13,1.59,432.20,444.60
JUBLFOOD.NS,5.24,-8.17,-11.58,-29.99,35.99,30.68,-0.32,-1.06,-12,-0.98,-1.14,-30,1.20,438.25,449.57
RELIANCE.NS,1.07,-8.17,-5.84,-3.19,22.50,20.10,-0.26,-0.75,-4,-0.16,-0.24,-2,0.90,1307.80,1335.54
HINDUNILVR.NS,-0.80,-5.70,-10.55,-19.57,25.91,21.83,-0.41,-0.70,-6,-0.90,-0.70,-19,0.72,2101.30,2180.99
PIIND.NS,7.67,-9.94,-13.76,-25.42,31.89,26.63,-0.43,-0.69,-4,-0.95,-1.41,-13,0.98,2751.20,2844.13
VMM.NS,-9.20,-12.42,-14.97,-28.32,33.80,29.45,-0.44,-0.68,-14,-0.96,-0.82,-28,0.97,107.10,117.65
ITC.NS,-2.07,-8.33,-8.52,-28.08,19.26,19.39,-0.44,-0.68,-2,-1.45,-1.72,-16,0.60,281.00,294.69
DRREDDY.NS,-14.86,-12.66,-5.15,-8.31,26.18,23.39,-0.20,-0.46,-16,-0.36,-0.14,-3,0.52,1148.10,1257.55
IREDA.NS,-7.07,-11.48,-8.98,-14.43,33.21,29.89,-0.27,-0.32,-2,-0.48,-0.56,-21,1.42,119.59,125.82
NBCC.NS,-9.65,3.44,-3.98,-3.22,37.34,35.33,-0.11,-0.16,-10,-0.09,-0.26,-27,1.69,94.80,98.69
COCHINSHIP.NS,-5.63,-17.91,-14.07,-10.98,40.66,37.14,-0.35,-0.01,-8,-0.30,-0.35,-20,1.40,1423.00,1479.68

In [27]:
outputBuy = stocksBuy.sort_values(rm[1], ascending = False)[:20].reset_index().rename(columns = {'index':'symbol'})
outputBuy

,Ticker,roc1M,roc3M,roc6M,roc12M,volatility6M,volatility12M,sharpe6MRoC,sharpe6M,FIP6M,sharpe12MRoC,sharpe12M,FIP12M,Beta,Close,ema100d
0,LAURUSLABS.NS,19.69,65.13,88.39,112.34,32.15,29.13,2.75,4.26,25,3.86,2.76,28,0.88,1816.20,1371.32
1,SOLARINDS.NS,-1.57,19.19,36.51,33.40,32.86,32.16,1.11,2.18,24,1.04,0.96,12,0.91,18391.00,16916.92
2,SONACOMS.NS,24.12,27.07,55.65,74.73,32.42,30.57,1.72,2.64,22,2.44,2.01,19,1.24,769.40,614.87
3,POWERINDIA.NS,-7.86,-4.10,70.58,68.37,44.34,43.17,1.59,2.64,22,1.58,1.20,26,0.81,32175.00,31151.12
4,FEDERALBNK.NS,8.73,25.06,24.71,87.18,25.90,24.98,0.95,1.90,21,3.49,2.61,36,0.94,358.85,310.84
5,CUMMINSIND.NS,-1.67,5.67,35.93,46.10,32.59,27.97,1.10,1.70,20,1.65,1.78,29,0.88,5519.00,5286.91
6,INDHOTEL.NS,3.45,16.67,10.04,-2.19,27.89,24.78,0.36,0.69,18,-0.09,0.09,21,1.38,738.55,693.01
7,TORNTPHARM.NS,10.88,22.65,30.48,45.18,24.35,21.40,1.25,2.36,18,2.11,1.81,22,0.28,5122.80,4526.50
8,ADANIENSOL.NS,10.33,22.59,83.88,115.32,39.51,38.24,2.12,2.75,18,3.02,2.11,21,1.50,1645.40,1433.05
9,INDUSINDBK.NS,9.55,10.70,13.17,37.13,33.70,29.04,0.39,0.81,15,1.28,0.96,13,1.46,1012.45,935.08
10,POLYCAB.NS,-8.58,12.81,30.46,29.03,32.41,29.04,0.94,1.40,14,1.00,1.12,23,1.06,9106.50,8854.12
11,BHEL.NS,-1.40,15.86,55.43,96.29,38.85,36.10,1.43,2.43,14,2.67,1.66,31,1.14,407.00,369.23
12,DIVISLAB.NS,22.96,24.40,33.68,31.93,21.73,22.93,1.55,2.61,14,1.39,1.02,10,0.60,8056.00,6751.24
13,SIEMENS.NS,4.96,-0.78,21.84,23.33,34.40,29.98,0.63,0.99,14,0.78,1.01,32,1.16,3760.00,3536.00
14,SUNPHARMA.NS,7.15,10.36,25.91,25.98,20.42,19.15,1.27,1.72,14,1.36,1.17,33,0.50,1990.50,1841.67
15,AUROPHARMA.NS,0.10,13.72,30.84,53.73,26.97,25.84,1.14,2.37,14,2.08,1.64,4,0.45,1580.20,1453.11
16,GODREJPROP.NS,13.35,15.29,34.19,8.63,36.87,34.92,0.93,1.45,13,0.25,0.20,11,1.92,2105.70,1879.52
17,SHRIRAMFIN.NS,1.00,12.30,3.20,82.51,41.98,35.17,0.08,0.50,13,2.35,1.70,32,1.98,1046.70,988.59
18,ABB.NS,3.61,0.75,31.12,46.32,33.16,29.22,0.94,1.65,12,1.59,1.41,27,1.03,7284.50,6814.04
19,PIDILITIND.NS,1.90,17.98,13.41,6.42,25.05,20.83,0.54,0.95,12,0.31,0.57,10,1.03,1611.40,1506.09

In [28]:
outputSell = stocksSell.sort_values(rm[1], ascending = True)[:30].reset_index().rename(columns = {'index':'symbol'})
outputSell

,Ticker,roc1M,roc3M,roc6M,roc12M,volatility6M,volatility12M,sharpe6MRoC,sharpe6M,FIP6M,sharpe12MRoC,sharpe12M,FIP12M,Beta,Close,ema100d
0,HDFCBANK.NS,-6.24,-1.45,-18.16,-20.08,27.14,20.85,-0.67,-1.56,-26,-0.96,-1.21,-35,1.27,748.15,793.48
1,INFY.NS,12.96,-2.31,-29.64,-20.23,33.86,29.67,-0.88,-1.51,-22,-0.68,-0.65,-26,0.76,1130.10,1164.78
2,INOXWIND.NS,-13.29,-22.60,-27.61,-43.43,44.41,37.44,-0.62,-1.25,-20,-1.16,-1.64,-38,1.83,78.14,90.28
3,DRREDDY.NS,-14.86,-12.66,-5.15,-8.31,26.18,23.39,-0.20,-0.46,-16,-0.36,-0.14,-3,0.52,1148.10,1257.55
4,HDFCLIFE.NS,-4.75,-6.21,-24.70,-28.70,25.94,21.90,-0.95,-2.02,-16,-1.31,-1.26,-23,0.88,548.50,598.68
5,RVNL.NS,-4.39,-24.25,-34.13,-25.25,34.17,34.14,-1.00,-1.87,-16,-0.74,-1.14,-43,1.51,225.48,256.44
6,VMM.NS,-9.20,-12.42,-14.97,-28.32,33.80,29.45,-0.44,-0.68,-14,-0.96,-0.82,-28,0.97,107.10,117.65
7,IRFC.NS,-1.52,-14.45,-24.98,-23.07,29.88,28.45,-0.84,-1.53,-13,-0.81,-1.13,-30,1.34,89.15,96.70
8,JUBLFOOD.NS,5.24,-8.17,-11.58,-29.99,35.99,30.68,-0.32,-1.06,-12,-0.98,-1.14,-30,1.20,438.25,449.57
9,AMBUJACEM.NS,2.45,-2.22,-14.86,-22.88,32.23,26.89,-0.46,-1.16,-10,-0.85,-1.12,-13,1.59,432.20,444.60
10,NBCC.NS,-9.65,3.44,-3.98,-3.22,37.34,35.33,-0.11,-0.16,-10,-0.09,-0.26,-27,1.69,94.80,98.69
11,COCHINSHIP.NS,-5.63,-17.91,-14.07,-10.98,40.66,37.14,-0.35,-0.01,-8,-0.30,-0.35,-20,1.40,1423.00,1479.68
12,WIPRO.NS,9.01,-7.43,-21.59,-23.60,26.38,25.01,-0.82,-1.66,-8,-0.94,-0.91,-5,0.74,183.65,189.56
13,ICICIPRULI.NS,5.63,0.65,-18.79,-13.78,29.94,24.48,-0.63,-1.49,-6,-0.56,-0.57,-1,1.02,515.40,525.61
14,HINDUNILVR.NS,-0.80,-5.70,-10.55,-19.57,25.91,21.83,-0.41,-0.70,-6,-0.90,-0.70,-19,0.72,2101.30,2180.99
15,KPITTECH.NS,-10.89,-21.16,-42.44,-49.62,46.19,39.04,-0.92,-1.88,-6,-1.27,-1.64,-23,0.99,598.40,713.53
16,TATAELXSI.NS,-4.09,-9.47,-29.77,-28.57,34.05,31.63,-0.87,-2.07,-6,-0.90,-1.38,-21,1.09,3672.90,4058.41
17,DALBHARAT.NS,5.83,-5.32,-12.61,-24.70,31.81,26.43,-0.40,-1.27,-6,-0.93,-0.83,-14,1.17,1799.70,1827.22
18,RELIANCE.NS,1.07,-8.17,-5.84,-3.19,22.50,20.10,-0.26,-0.75,-4,-0.16,-0.24,-2,0.90,1307.80,1335.54
19,PIIND.NS,7.67,-9.94,-13.76,-25.42,31.89,26.63,-0.43,-0.69,-4,-0.95,-1.41,-13,0.98,2751.20,2844.13
20,PATANJALI.NS,-13.73,-22.82,-28.87,-39.69,29.45,25.55,-0.98,-2.45,-4,-1.55,-2.06,-3,0.77,354.60,429.27
21,ITC.NS,-2.07,-8.33,-8.52,-28.08,19.26,19.39,-0.44,-0.68,-2,-1.45,-1.72,-16,0.60,281.00,294.69
22,IREDA.NS,-7.07,-11.48,-8.98,-14.43,33.21,29.89,-0.27,-0.32,-2,-0.48,-0.56,-21,1.42,119.59,125.82
23,DABUR.NS,1.12,-3.30,-15.73,-17.64,26.51,23.43,-0.59,-1.17,-1,-0.75,-0.80,-15,0.99,421.45,440.43